#
# makefile
#
# Copyright (C) STMicroelectronics Limited 2003. All rights reserved.
#
# Makefile for rpc examples directory
#

RPC_ROOT = ../..
SUBDIRS = getstart posthoc strategy tricks

DIST_SRC = makefile

include $(RPC_ROOT)/src/mkfiles/host.mak
include $(RPC_ROOT)/src/mkfiles/subdir.mak

include $(RPC_ROOT)/src/mkfiles/install.mak
