#
# makefile
#
# Copyright (C) STMicroelectronics R&D Ltd. 2002
#
# Makefile for platform source subtree
#

RPC_ROOT = ../..

include $(RPC_ROOT)/src/mkfiles/host.mak

SUBDIRS = mb385 sim231

include $(RPC_ROOT)/src/mkfiles/subdir.mak

DIST_SRC       = makefile

include $(RPC_ROOT)/src/mkfiles/install.mak
