#ifdef ST_OSLINUX
   #include "stos.h"
#else
/*C libs */
#include "string.h"
#endif

#include "361_init.h"
#include "chip.h"

#ifdef HOST_PC
#include "gen_types.h"
#endif
#include "361_map.h"


/*********To ADD Array consisting addresses of STV0361*****************/
U8 Def361Addr[STV361_NBREGS]={
/* R_ID*/		0x00,
/*R_I2CRPT*/		0x01,
/*R_TOPCTRL*/		0x02,
/*R_IOCFG0*/		0x03,
/*R_DAC0R*/		0x04,
/*R_IOCFG1*/            0x05,
/*R_DAC1R*/		0x06,
/*R_IOCFG2*/		0x07,
/*R_SDFR*/		0x08,
/*R_STATUS*/		0x09,

/*R_AUX_CLK*/		0x0A,
/*R_RESERVED_1*/	0x0B,
/*R_RESERVED_2*/	0x0C,
/*R_RESERVED_3*/	0x0D,
/*R_AGC2MAX*/		0x10,

/*R_AGC2MIN*/		0x11,
/*R_AGC1MAX*/		0x12,
/*R_AGC1MIN*/		0x13,
/*R_AGCR*/		0x14,
/*R_AGC2TH*/		0x15,

/*R_AGC12C*/		0x16,
/*R_AGCCTRL1*/		0x17,
/*R_AGCCTRL2*/		0x18,
/*R_AGC1VAL1*/		0x19,
/*R_AGC1VAL2*/		0x1A,

/*R_AGC2VAL1*/		0x1B,
/*R_AGC2VAL2*/		0x1C,
/*R_AGC2PGA*/		0x1D,
/*R_OVF_RATE1*/		0x1E,
/*R_OVF_RATE2*/		0x1F,

/*R_GAIN_SRC1*/		0x20,
/*R_GAIN_SRC2*/		0x21,
/*R_INC_DEROT1*/	0x22,
/*R_INC_DEROT2*/	0x23,
/*R_PPM_CPAMP_DIR*/	0x24,

/*R_PPM_CPAMP_INV*/	0x25,
/*R_FREESTFE_1*/	0x26,
/*R_FREESTFE_2*/	0x27,
/*R_DCOFFSET*/		0x28,
/*R_EN_PROCESS*/	0x29,
/*R_RESERVED_4*/	0x2A,

/*R_RESERVED_5*/	0x2B,
/*R_RESERVED_6*/	0x2C,
/*R_RESERVED_7*/	0x2D,
/*R_RESERVED_8*/	0x2E,
/*R_RESERVED_9*/	0x2F,

/*R_RESERVED_10*/	0x30,
/*R_EPQ*/		0x31,
/*R_EPQAUTO*/		0x32,
/*R_CHP_TAPS*/		0x33,
/*R_CHP_DYN_COEFF*/	0x34,

/*R_PPM_STATE_MAC*/	0x35,
/*R_INR_THRESHOLD*/	0x36,
/*R_COR_CTL*/		0x80,
/*R_COR_STAT*/		0x81,
/*R_COR_INTEN*/		0x82,

/*R_COR_INTSTAT*/	0x83,
/*R_COR_MODEGUARD*/	0x84,
/*R_AGC_CTL*/		0x85,
/*R_RESERVED_11*/	0x86,
/*R_RESERVED_12*/	0x87,

/*R_AGC_TARGET*/	0x88,
/*R_AGC_GAIN1*/		0x89,
/*R_AGC_GAIN2*/		0x8A,
/*R_RESERVED_13*/	0x8B,
/*R_RESERVED_14*/	0x8C,

/*R_RESERVED_15*/	0x8D,
/*R_CAS_CTL*/		0x8E,
/*R_CAS_FREQ*/		0x8F,
/*R_CAS_DAGCGAIN*/	0x90,
/*R_SYR_CTL*/		0x91,

/*R_SYR_STAT*/		0x92,
/*R_RESERVED_16*/	0x93,
/*R_RESERVED_17*/	0x94,
/*R_SYR_OFFSET1*/	0x95,
/*R_SYR_OFFSET2*/	0x96,

/*R_RESERVED_18*/	0x97,
/*R_SCR_CTL*/		0x98,
/*R_PPM_CTL1*/		0x99,
/*R_TRL_CTL*/		0x9A,
/*R_TRL_NOMRATE1*/	0x9B,

/*R_TRL_NOMRATE2*/	0x9C,
/*R_TRL_TIME1*/		0x9D,
/*R_TRL_TIME2*/		0x9E,
/*R_CRL_CTL*/		0x9F,
/*R_CRL_FREQ1*/		0xA0,

/*R_CRL_FREQ2*/		0xA1,
/*R_CRL_FREQ3*/		0xA2,
/*R_CHC_CTL1*/		0xA3,
/*R_CHC_SNR*/		0xA4,
/*R_BDI_CTL*/		0xA5,


/*R_DMP_CTL*/		0xA6,
/*R_TPS_RCVD1*/		0xA7,
/*R_TPS_RCVD2*/		0xA8,
/*R_TPS_RCVD3*/		0xA9,
/*R_TPS_RCVD4*/		0xAA,

/*R_TPS_ID_CELL1*/	0xAB,
/*R_TPS_ID_CELL2*/	0xAC,
/*R_RESERVED_19*/	0xAD,
/*R_RESERVED_20*/	0xAE,
/*R_RESERVED_21*/	0xAF,

/*R_TPS_CTL*/		0xB0,
/*R_CTL_FFTOSNUM */	0xB1,
/*R_TESTSELECT*/	0xB2,
/*R_MSC_REV*/		0xB3,
/*R_PIR_CTL*/		0xB4,

/*R_SNR_CARRIER1*/	0xB5,
/*R_SNR_CARRIER2*/	0xB6,
/*R_RESERVED_22 */	0xB7,
/*R_RESERVED_23*/	0xB8,
/*R_RESERVED_24*/	0xB9,

/*R_RESERVED_25*/	0xBA,
/*R_RESERVED_26*/	0xBB,
/*R_RESERVED_27*/	0xBC,
/*R_RESERVED_28*/	0xBD,
/*R_RESERVED_29*/	0xBE,

/*R_RESERVED_30*/	0xBF,
/*R_RESERVED_31*/	0x40,
/*R_VTH0*/		0x41,
/*R_VTH1*/		0x42,
/*R_VTH2*/		0x43,

/*R_VTH3*/		0x44,
/*R_RESERVED_32*/	0x45,
/*R_VTH5*/		0x46,
/*R_RESERVED_33*/	0x47,
/*R_VITPROG*/		0x49,

/*R_PR*/		0x4A,
/*R_VSEARCH*/		0x4B,
/*R_RS*/		0x4C,
/*R_RSOUT*/		0x4D,
/*R_ERRCTRL1*/		0x4E,

/*R_ERRCNTM1*/		0x4F,
/*R_ERRCNTL1*/		0x50,
/*R_ERRCTRL2*/		0x51,
/*R_ERRCNTM2*/		0x52,
/*R_ERRCNTL2*/		0x53,

/*R_RESERVED_34*/	0x54,
/*R_VERROR*/		0x55,
/*R_ERRCTRL3*/		0x56,
/*R_ERRCNTM3*/		0x57,
/*R_ERRCNTL3*/		0x58,

/*R_RESERVED_35*/	0x59,
/*R_RESERVED_36*/	0x5A,
/*R_RESERVED_37*/	0x5B,
/*R_RESERVED_38*/	0x5C,
/*R_LNBRX*/		0x5D,

/*R_RESERVED_39*/	0x5E,
/*R_RESERVED_40*/	0x5F,
/*R_RESERVED_41*/	0xC0,
/*R_ANACTRL*/		0xC1,
/*R_RESERVED_42*/	0xC2,

/*R_RESERVED_43*/	0xC3,
/*R_RESERVED_44*/	0xC4,
/*R_RESERVED_45*/	0xC5,
/*R_RESERVED_46*/	0xC6,
/*R_RESERVED_47*/	0xC7,

/*R_RESERVED_48*/	0xC8,
/*R_RESERVED_49*/	0xC9,
/*R_RESERVED_50*/	0xCA,
/*R_CONSTMODE*/		0xCB,
/*R_CONSTCARR1*/	0xCC,

/*R_CONSTCARR2*/	0xCD,
/*R_ICONSTEL*/		0xCE,
/*R_QCONSTEL*/		0xCF,
/*R_RESERVED_51*/	0xD0,
/*R_RESERVED_52*/	0xD1,

/*R_RESERVED_53*/	0xD2,
/*R_RESERVED_54*/	0xD3,
/*R_RF_AGC1*/		0xD4,
/*R_RF_AGC2*/		0xD5,
/*R_RESERVED_55*/	0xD6,

/*R_ANACTRL2*/		0xDB,
/*R_PLLMDIV*/		0xD8,
/*R_PLLNDIV*/		0xD9,
/*R_PLLSETUP*/		0xDA,
/*R_ANADIGCTRL*/	0xD7,
/*R_TSTBIST*/		0xDC
};


STCHIP_Handle_t STV0361_Init(STV0361_InitParams_t *InitParams)
{
    STCHIP_Handle_t hChip;
    U8             *DefVal;
    ST_ErrorCode_t Error=ST_NO_ERROR;
    int count=0;

    /*
    **   REGISTER CONFIGURATION
    **     ----------------------
    */


	/* fill elements of external chip data structure */
	

#ifndef STTUNER_REG_INIT_OLD_METHOD 
U8 *Addr;
U8 fieldpattern[] ={ 0x00,0x75,0x55,0x50,0x00,0x50,0x00,0x17,
		     0x0F,0x57,0x26,0x00,0x00,0x00,0x00,0x00,
		     0x00,0x00,0x18,0x00,0x54,0x48,0x67,0x00,
		     0x0F,0x00,0x0F,0x3F,0x0F,0x00,0x50,0x00,
		     0x00,0x00,0x00,0x00,0x3A,0x20,0x7F,0x0E,
		     0x7F,0x02,0x00,0x00,0x00,0x00,0x00,0x00,
		     0x00,0x02,0x7F,0x20,0x7F,0x2F,0x50,0x55,
		     0x2A,0x0B,0x2A,0x00,0x0F,0x00,0x00,0x10,
		     0x01,0x00,0x3F,0x58,0x00,0x00,0x7A,0x14,
		     0x00,0x3F,0x00,0x3f,0x1A,0x72,0x4A,0x78,
		     0x00,0x00,0x00,0x00,0x78,0x00,0x00,0x7F,
		     0x15,0x00,0x02,0x1E,0x53,0x73,0x77,0x33,
		     0x00,0x00,0x03,0x73,0x77,0x05,0x7F,0x1F,
		     0x00,0x01,0x00,0x60,0x00,0x00,0x00,0x00,
		     0x00,0x00,0x00,0x00,0x00,0x0A,0x7F,0x7F,
		     0x7F,0x7F,0x7F,0x7F,0x00,0x33,0x55,0x4C,
		     0x55,0x10,0x4B,0x00,0x00,0x4B,0x00,0x00,
		     0x00,0x00,0x4B,0x00,0x00,0x00,0x00,0x00,
		     0x00,0x48,0x55,0x47,0x55,0x55,0x47,0x75,
		     0x68,0x5C,0x68,0x55,0x55,0x05,0x4D,0x1B,
		     0x00,0x1F,0x00,0x00,0x55,0x55,0x55,0x55,
		     0x00,0x5B,0x00,0x00,0x00,0x00,0x70,0x2A,
		     0x29};

	
			     
        U8 Rindex = 0;
	U16 Findex = 0;
	U8 fieldwidth = 1;
	U8 bitvalue = 0;
	U8 temppatternstore = 0;
	S8 bitposition = 7;
	
    Addr = Def361Addr;
    InitParams->Chip->NbRegs   = STV361_NBREGS;
    InitParams->Chip->NbFields = STV361_NBFIELDS;
    InitParams->Chip->ChipMode = STCHIP_MODE_SUBADR_8;

    if(InitParams->NbDefVal == STV361_NBREGS)
    {
        hChip = ChipOpen(InitParams->Chip);

        DefVal = InitParams->DefVal;

if(hChip != NULL)
{
	for (Rindex=0;Rindex<STV361_NBREGS;Rindex++)
	{
		ChipAddReg(hChip,Rindex,"\0",*Addr++ ,*DefVal++,STCHIP_ACCESS_WR);
		temppatternstore=fieldpattern[Rindex];
		bitvalue = 0;
		for (bitposition=7;bitposition>=0;bitposition--)
		{
				temppatternstore = temppatternstore<<1;
				if (((temppatternstore & 0x80/*1000 0000*/)==bitvalue) && (bitposition!=0))
				{
					fieldwidth++;
				}
				else
				{
					ChipAddField(hChip,Rindex,Findex,"\0",bitposition,fieldwidth,CHIP_UNSIGNED);								
					fieldwidth=1;
					Findex++;
					bitvalue = ((bitvalue==0) ? (bitvalue=0x80) : (bitvalue=0));
				}
		}/*end for loop on bitposition*/
	}/*end for loop on Rindex*/
}
}
else
{
   return (STCHIP_Handle_t) NULL;
}
#else /*#ifndef STTUNER_REG_INIT_OLD_METHOD*/

	InitParams->Chip->NbRegs   = STV361_NBREGS;
	InitParams->Chip->NbFields = STV361_NBFIELDS;
	InitParams->Chip->ChipMode = STCHIP_MODE_SUBADR_8;

    if(InitParams->NbDefVal != STV361_NBREGS) return (STCHIP_Handle_t) NULL;

    hChip = ChipOpen(InitParams->Chip);

	 	DefVal=InitParams->DefVal;


	if(hChip != NULL)
	
	{


				/*	REGISTER INITIALISATION	*/
/*	ID	00000000*/
ChipAddReg(hChip,R_ID,"ID",0x0000,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ID,IDENTIFICATIONREGISTER,"IDENTIFICATIONREGISTER",0,8,CHIP_UNSIGNED);

/*	I2CRPT	01110101*/
ChipAddReg(hChip,R_I2CRPT,"I2CRPT",0x0001,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_I2CRPT,I2CT_ON,"I2CT_ON",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_I2CRPT,ENARPT_LEVEL,"ENARPT_LEVEL",4,3,CHIP_UNSIGNED);
ChipAddField(hChip,R_I2CRPT,SCLT_DELAY,"SCLT_DELAY",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_I2CRPT,SCLT_NOD,"SCLT_NOD",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_I2CRPT,STOP_ENABLE,"STOP_ENABLE",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_I2CRPT,SDAT_NOD,"SDAT_NOD",0,1,CHIP_UNSIGNED);

/*	TOPCTRL	01010101*/
ChipAddReg(hChip,R_TOPCTRL,"TOPCTRL",0x0002,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TOPCTRL,STDBY,"STDBY",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TOPCTRL,STDBY_FEC,"STDBY_FEC",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TOPCTRL,STDBY_CORE,"STDBY_CORE",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TOPCTRL,DIR_CLK,"DIR_CLK",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TOPCTRL,TS_DIS,"TS_DIS",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TOPCTRL,DUAL_CKDIR,"DUAL_CKDIR",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TOPCTRL,BYP_BUFFER,"BYP_BUFFER",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TOPCTRL,ENA_27,"ENA_27",0,1,CHIP_UNSIGNED);

/*	IOCFG0	01010000*/
ChipAddReg(hChip,R_IOCFG0,"IOCFG0",0x0003,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_IOCFG0,OP0_SD,"OP0_SD",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_IOCFG0,OP0_VAL,"OP0_VAL",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_IOCFG0,OP0_OD,"OP0_OD",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_IOCFG0,OP0_INV,"OP0_INV",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_IOCFG0,OP0_DACVALUE_HI,"OP0_DACVALUE_HI",0,4,CHIP_UNSIGNED);

/*	DAC0R	00000000 */
ChipAddReg(hChip,R_DAC0R,"DAC0R",0x0004,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_DAC0R,OP0_DACVALUE_LO,"OP0_DACVALUE_LO",0,8,CHIP_UNSIGNED);

/*	IOCFG1	R1010000-->01010000*/
ChipAddReg(hChip,R_IOCFG1,"IOCFG1",0x0005,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_IOCFG1,IP0,"IP0",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_IOCFG1,OP1_OD,"OP1_OD",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_IOCFG1,OP1_INV,"OP1_INV",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_IOCFG1,OP1_DACVALUE_HI,"OP1_DACVALUE_HI",0,4,CHIP_UNSIGNED);

/*	DAC1R	00000000*/
ChipAddReg(hChip,R_DAC1R,"DAC1R",0x0006,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_DAC1R,OP1_DACVALUE_LO,"OP1_DACVALUE_LO",0,8,CHIP_UNSIGNED);

/*	IOCFG2	00010111*/
ChipAddReg(hChip,R_IOCFG2,"IOCFG2",0x0007,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_IOCFG2,OP2_LOCK_CONF,"OP2_LOCK_CONF",5,3,CHIP_UNSIGNED);
ChipAddField(hChip,R_IOCFG2,OP2_OD,"OP2_OD",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_IOCFG2,OP2_VAL,"OP2_VAL",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_IOCFG2,OP1_LOCK_CONF,"OP1_LOCK_CONF",0,3,CHIP_UNSIGNED);

/*	SDFR	00001111*/
ChipAddReg(hChip,R_SDFR,"SDFR",0x0008,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_SDFR,OP0_FREQ,"OP0_FREQ",4,4,CHIP_UNSIGNED);
ChipAddField(hChip,R_SDFR,OP1_FREQ,"OP1_FREQ",0,4,CHIP_UNSIGNED);

/*	STATUS	01010111*/
ChipAddReg(hChip,R_STATUS,"STATUS",0x0009,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_STATUS,TPS_LOCK,"TPS_LOCK",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_STATUS,SYR_LOCK,"SYR_LOCK",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_STATUS,AGC_LOCK,"AGC_LOCK",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_STATUS,PRF,"PRF",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_STATUS,LK,"LK",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_STATUS,PR,"PR",0,3,CHIP_UNSIGNED);

/*	AUX_CLK 00100110	*/
ChipAddReg(hChip,R_AUX_CLK,"AUX_CLK",0x000a,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AUX_CLK,AUXFEC_CTL,"AUXFEC_CTL",6,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_AUX_CLK,DIS_CKX4,"DIS_CKX4",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AUX_CLK,CKSEL,"CKSEL",3,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_AUX_CLK,CKDIV_PROG,"CKDIV_PROG",1,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_AUX_CLK,AUXCLK_ENA,"AUXCLK_ENA",0,1,CHIP_UNSIGNED);

/*	R_RESERVED_1 RRRRRRRR-->00000000 */
ChipAddReg(hChip,R_RESERVED_1,"RESERVED_1",0x000b,*DefVal++,STCHIP_ACCESS_WR);

/*	R_RESERVED_2 RRRRRRRR-->00000000 */
ChipAddReg(hChip,R_RESERVED_2,"RESERVED_2",0x000c,*DefVal++,STCHIP_ACCESS_WR);

/*	RESERVED_3   RRRRRRRR-->00000000 */
ChipAddReg(hChip,R_RESERVED_3,"RESERVED_3",0x000d,*DefVal++,STCHIP_ACCESS_WR);

/*	AGC2MAX	00000000*/
ChipAddReg(hChip,R_AGC2MAX,"AGC2MAX",0x0010,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC2MAX,AGC2MAX,"AGC2MAX",0,8,CHIP_UNSIGNED);

/*	AGC2MIN	00000000*/
ChipAddReg(hChip,R_AGC2MIN,"AGC2MIN",0x0011,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC2MIN,AGC2MIN,"AGC2MIN",0,8,CHIP_UNSIGNED);

/*	AGC1MAX 00000000 */
ChipAddReg(hChip,R_AGC1MAX,"AGC1MAX",0x0012,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC1MAX,AGC1MAX,"AGC1MAX",0,8,CHIP_UNSIGNED);

/*	AGC1MIN	00000000*/
ChipAddReg(hChip,R_AGC1MIN,"AGC1MIN",0x0013,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC1MIN,AGC1MIN,"AGC1MIN",0,8,CHIP_UNSIGNED);

/*	AGCR	00011000*/
ChipAddReg(hChip,R_AGCR,"AGCR",0x0014,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGCR,RATIO_A,"RATIO_A",5,3,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGCR,RATIO_B,"RATIO_B",3,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGCR,RATIO_C,"RATIO_C",0,3,CHIP_UNSIGNED);

/*	AGC2TH	00000000*/
ChipAddReg(hChip,R_AGC2TH,"AGC2TH",0x0015,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC2TH,AGC2_THRES,"AGC2_THRES",0,8,CHIP_UNSIGNED);

/*	AGC12C	01010100*/
ChipAddReg(hChip,R_AGC12C,"AGC12C",0x0016,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC12C,AGC1_IV,"AGC1_IV",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGC12C,AGC1_OD,"AGC1_OD",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGC12C,AGC1_LOAD,"AGC1_LOAD",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGC12C,AGC2_IV,"AGC2_IV",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGC12C,AGC2_OD,"AGC2_OD",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGC12C,AGC2_LOAD,"AGC2_LOAD",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGC12C,AGC12_MODE,"AGC12_MODE",0,2,CHIP_UNSIGNED);

/*	AGCCTRL1 01RR1000-->01001000 */
ChipAddReg(hChip,R_AGCCTRL1,"AGCCTRL1",0x0017,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGCCTRL1,DAGC_ON,"DAGC_ON",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGCCTRL1,INVERT_AGC12,"INVERT_AGC12",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGCCTRL1,AGC1_MODE,"AGC1_MODE",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGCCTRL1,AGC2_MODE,"AGC2_MODE",0,3,CHIP_UNSIGNED);

/*	AGCCTRL2	R1100111->01100111*/
ChipAddReg(hChip,R_AGCCTRL2,"AGCCTRL2",0x0018,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGCCTRL2,FRZ2_CTRL,"FRZ2_CTRL",5,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGCCTRL2,FRZ1_CTRL,"FRZ1_CTRL",3,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGCCTRL2,TIME_CST,"TIME_CST",0,3,CHIP_UNSIGNED);

/*	AGC1VAL1	00000000*/
ChipAddReg(hChip,R_AGC1VAL1,"AGC1VAL1",0x0019,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC1VAL1,AGC1_VAL_LO,"AGC1_VAL_LO",0,8,CHIP_UNSIGNED);

/*	AGC1VAL2	RRRR1111-->00001111*/
ChipAddReg(hChip,R_AGC1VAL2,"AGC1VAL2",0x001a,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC1VAL2,AGC1_VAL_HI,"AGC1_VAL_HI",0,4,CHIP_UNSIGNED);

/*	AGC2VAL1	00000000*/
ChipAddReg(hChip,R_AGC2VAL1,"AGC2VAL1",0x001b,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC2VAL1,AGC2_VAL_LO,"AGC2_VAL_LO",0,8,CHIP_UNSIGNED);

/*	AGC2VAL2	RRRR1111-->00001111 */
ChipAddReg(hChip,R_AGC2VAL2,"AGC2VAL2",0x001c,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC2VAL2,AGC2_VAL_HI,"AGC2_VAL_HI",0,4,CHIP_UNSIGNED);

/*	AGC2PGA RR111111-->00111111*/
ChipAddReg(hChip,R_AGC2PGA,"AGC2PGA",0x001d,*DefVal++,STCHIP_ACCESS_WR);
/*if (strcmp(InitParams->Chip->Name,"STV0360")==0)*/
ChipAddField(hChip,R_AGC2PGA,UAGC2PGA,"UAGC2PGA",0,6,CHIP_UNSIGNED);

/*	OVF_RATE1	RRRR1111-->00001111 */
ChipAddReg(hChip,R_OVF_RATE1,"OVF_RATE1",0x001e,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_OVF_RATE1,OVF_RATE_HI,"OVF_RATE_HI",0,4,CHIP_UNSIGNED);

/*	OVF_RATE2 00000000 */
ChipAddReg(hChip,R_OVF_RATE2,"OVF_RATE2",0x001f,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_OVF_RATE2,OVF_RATE_LO,"OVF_RATE_LO",0,8,CHIP_UNSIGNED);

/*	GAIN_SRC1 01010000	*/
ChipAddReg(hChip,R_GAIN_SRC1,"GAIN_SRC1",0x0020,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_GAIN_SRC1,INV_SPECTR,"INV_SPECTR",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_GAIN_SRC1,IQ_INVERT,"IQ_INVERT",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_GAIN_SRC1,INR_BYPASS,"INR_BYPASS",5,1,CHIP_UNSIGNED);
/*if (strcmp(InitParams->Chip->Name,"STV0360")!=0)*/
ChipAddField(hChip,R_GAIN_SRC1,INS_BYPASS,"INS_BYPASS",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_GAIN_SRC1,GAIN_SRC_HI,"GAIN_SRC_HI",0,4,CHIP_UNSIGNED);

/*	GAIN_SRC2 00000000 */
ChipAddReg(hChip,R_GAIN_SRC2,"GAIN_SRC2",0x0021,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_GAIN_SRC2,GAIN_SRC_LO,"GAIN_SRC_LO",0,8,CHIP_UNSIGNED);

/*	INC_DEROT1 00000000*/
ChipAddReg(hChip,R_INC_DEROT1,"INC_DEROT1",0x0022,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_INC_DEROT1,INC_DEROT_HI,"INC_DEROT_HI",0,8,CHIP_UNSIGNED);

/*	INC_DEROT2 00000000	*/
ChipAddReg(hChip,R_INC_DEROT2,"INC_DEROT2",0x0023,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_INC_DEROT2,INC_DEROT_LO,"INC_DEROT_LO",0,8,CHIP_UNSIGNED);


/*	PPM_CPAMP_DIR 00000000	*/
ChipAddReg(hChip,R_PPM_CPAMP_DIR,"PPM_CPAMP_DIR",0x0024,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_PPM_CPAMP_DIR,PPM_CPAMP_DIRECT,"PPM_CPAMP_DIRECT",0,8,CHIP_UNSIGNED);

/*	PPM_CPAMP_INV 00000000	*/
ChipAddReg(hChip,R_PPM_CPAMP_INV,"PPM_CPAMP_INV",0x0025,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_PPM_CPAMP_INV,PPM_CPAMP_INV,"PPM_CPAMP_INV",0,8,CHIP_UNSIGNED);

/*	FREESTFE_1 00RRR010-->00111010	*/
ChipAddReg(hChip,R_FREESTFE_1,"FREESTFE_1",0x0026,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_FREESTFE_1,SYMBOL_NUMBER_INC,"SYMBOL_NUMBER_INC",6,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_FREESTFE_1,SEL_LSB,"SEL_LSB",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_FREESTFE_1,AVERAGE_ON,"AVERAGE_ON",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_FREESTFE_1,DC_ADJ,"DC_ADJ",0,1,CHIP_UNSIGNED);

/*	FREESTFE_2 00R00000-->00100000*/  /*SYR_THR dans une des versions du STV0360*/
ChipAddReg(hChip,R_FREESTFE_2,"FREESTFE_2",0x0027,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_FREESTFE_2,SEL_SRCOUT,"SEL_SRCOUT",6,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_FREESTFE_2,SEL_SYRTHR,"SEL_SYRTHR",0,5,CHIP_UNSIGNED);

/*	DCOFFSET  R1111111-->01111111*/
ChipAddReg(hChip,R_DCOFFSET,"DCOFFSET",0x0028,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_DCOFFSET,DC_OFFSET,"DC_OFFSET",0,7,CHIP_UNSIGNED);

/*	EN_PROCESS	0000RRR0-->00001110*/
ChipAddReg(hChip,R_EN_PROCESS,"EN_PROCESS",0x0029,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_EN_PROCESS,INS_NIN_INDEX,"INS_NIN_INDEX",4,4,CHIP_UNSIGNED);
ChipAddField(hChip,R_EN_PROCESS,ENAB_MANUAL,"ENAB_MANUAL",0,1,CHIP_UNSIGNED);

/*	RESERVED_4	01111111*/
ChipAddReg(hChip,R_RESERVED_4,"RESERVED_4",0x002a,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_4,DIS_SMOOTH,"DIS_SMOOTH",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_4,SDI_INC_SMOOTHER,"SDI_INC_SMOOTHER",0,7,CHIP_UNSIGNED);

/*	RESERVED_5 RRRRRR10-->00000010*/
ChipAddReg(hChip,R_RESERVED_5,"RESERVED_5",0x002b,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_5,TRL_LOOP_OP,"TRL_LOOP_OP",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_5,CRL_LOOP_OP,"CRL_LOOP_OP",0,1,CHIP_UNSIGNED);

/*	RESERVED_6 00000000*/
ChipAddReg(hChip,R_RESERVED_6,"RESERVED_6",0x002c,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_6,FREQ_OFFSET_LOOP_OPEN_VHI,"FREQ_OFFSET_LOOP_OPEN_VHI",0,8,CHIP_UNSIGNED);

/*	RESERVED_7 00000000	*/
ChipAddReg(hChip,R_RESERVED_7,"RESERVED_7",0x002d,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_7,FREQ_OFFSET_LOOP_OPEN_HI,"FREQ_OFFSET_LOOP_OPEN_HI",0,8,CHIP_UNSIGNED);

/*	RESERVED_8 00000000	*/
ChipAddReg(hChip,R_RESERVED_8,"RESERVED_8",0x002e,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_8,FREQ_OFFSET_LOOP_OPEN_LO,"FREQ_OFFSET_LOOP_OPEN_LO",0,8,CHIP_UNSIGNED);

/*	RESERVED_9 00000000	*/
ChipAddReg(hChip,R_RESERVED_9,"RESERVED_9",0x002f,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_9,TIM_OFFSET_LOOP_OPEN_HI,"TIM_OFFSET_LOOP_OPEN_HI",0,8,CHIP_UNSIGNED);

/*	RESERVED_10 00000000	*/
ChipAddReg(hChip,R_RESERVED_10,"RESERVED_10",0x0030,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_10,TIM_OFFSET_LOOP_OPEN_LO,"TIM_OFFSET_LOOP_OPEN_LO",0,8,CHIP_UNSIGNED);

/*	EPQ	00000000 */
ChipAddReg(hChip,R_EPQ,"EPQ",0x0031,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_EPQ,EPQ,"EPQ",0,8,CHIP_UNSIGNED);

/*	EPQAUTO	00000000 */
ChipAddReg(hChip,R_EPQAUTO,"EPQAUTO",0x0032,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_EPQAUTO,EPQ2,"EPQ2",0,8,CHIP_UNSIGNED);

/*	CHP_TAPS  RRRRRR10-->00000010*/
ChipAddReg(hChip,R_CHP_TAPS,"CHP_TAPS",0x0033,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CHP_TAPS,SCAT_FILT_EN,"SCAT_FILT_EN",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_CHP_TAPS,TAPS_EN,"TAPS_EN",0,1,CHIP_UNSIGNED);

/*	CHP_DYN_COEFF 0RRRRRRR-->01111111*/
ChipAddReg(hChip,R_CHP_DYN_COEFF,"CHP_DYN_COEFF",0x0034,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CHP_DYN_COEFF,CHP_DYNAM_COEFFCIENT,"CHP_DYNAM_COEFFCIENT",7,1,CHIP_UNSIGNED);

/*	PPM_STATE_MAC 	RR1RRRRR-->00100000*/
ChipAddReg(hChip,R_PPM_STATE_MAC,"PPM_STATE_MAC",0x0035,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_PPM_STATE_MAC,PPM_STATE_MACHINE_DECODER,"PPM_STATE_MACHINE_DECODER",5,1,CHIP_UNSIGNED);

/*	INR_THRESHOLD 0RRRRRRR-->01111111*/
ChipAddReg(hChip,R_INR_THRESHOLD,"INR_THRESHOLD",0x0036,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_INR_THRESHOLD,INR_THRESHOLD,"INR_THRESHOLD",7,1,CHIP_UNSIGNED);


/*	COR_CTL RR101111-->00101111*/
ChipAddReg(hChip,R_COR_CTL,"COR_CTL",0x0080,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_COR_CTL,CORE_ACTIVE,"CORE_ACTIVE",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_CTL,HOLD,"HOLD",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_CTL,CORE_STATE_CTL,"CORE_STATE_CTL",0,4,CHIP_UNSIGNED);

/*	COR_STAT 01010000	*/
ChipAddReg(hChip,R_COR_STAT,"COR_STAT",0x0081,*DefVal++,STCHIP_ACCESS_WR);
/*This Field is RESERVED in 2.1 version*/
ChipAddField(hChip,R_COR_STAT,SCATT_LOCKED,"SCATT_LOCKED",7,1,CHIP_UNSIGNED);
/*****************************************/
ChipAddField(hChip,R_COR_STAT,TPS_LOCKED,"TPS_LOCKED",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_STAT,SYR_LOCKED_COR,"SYR_LOCKED_COR",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_STAT,AGC_LOCKED_STAT,"AGC_LOCKED_STAT",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_STAT,CORE_STATE_STAT,"CORE_STATE_STAT",0,4,CHIP_UNSIGNED);

/*	COR_INTEN 0R010101-->01010101	*/
ChipAddReg(hChip,R_COR_INTEN,"COR_INTEN",0x0082,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_COR_INTEN,INTEN,"INTEN",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_INTEN,INTEN_SYR,"INTEN_SYR",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_INTEN,INTEN_FFT,"INTEN_FFT",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_INTEN,INTEN_AGC,"INTEN_AGC",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_INTEN,INTEN_TPS1,"INTEN_TPS1",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_INTEN,INTEN_TPS2,"INTEN_TPS2",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_INTEN,INTEN_TPS3,"INTEN_TPS3",0,1,CHIP_UNSIGNED);

/*	COR_INTSTAT	RR101010-->00101010*/
ChipAddReg(hChip,R_COR_INTSTAT,"COR_INTSTAT",0x0083,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_COR_INTSTAT,INTSTAT_SYR,"INTSTAT_SYR",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_INTSTAT,INTSTAT_FFT,"INTSTAT_FFT",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_INTSTAT,INTSAT_AGC,"INTSAT_AGC",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_INTSTAT,INTSTAT_TPS1,"INTSTAT_TPS1",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_INTSTAT,INTSTAT_TPS2,"INTSTAT_TPS2",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_INTSTAT,INTSTAT_TPS3,"INTSTAT_TPS3",0,1,CHIP_UNSIGNED);

/*	COR_MODEGUARD RRRR1011-->00001011*/
ChipAddReg(hChip,R_COR_MODEGUARD,"COR_MODEGUARD",0x0084,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_COR_MODEGUARD,FORCE,"FORCE",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_MODEGUARD,MODE,"MODE",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_COR_MODEGUARD,GUARD,"GUARD",0,2,CHIP_UNSIGNED);

/*	AGC_CTL 00R0101R-->00101010	*/
ChipAddReg(hChip,R_AGC_CTL,"AGC_CTL",0x0085,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC_CTL,AGC_TIMING_FACTOR,"AGC_TIMING_FACTOR",6,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGC_CTL,AGC_LAST,"AGC_LAST",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGC_CTL,AGC_GAIN,"AGC_GAIN",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGC_CTL,AGC_NEG,"AGC_NEG",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGC_CTL,AGC_SET,"AGC_SET",1,1,CHIP_UNSIGNED);

/*	RESERVED_11 00000000 */
ChipAddReg(hChip,R_RESERVED_11,"RESERVED_11",0x0086,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_11,AGC_VAL_LO,"AGC_VAL_LO",0,8,CHIP_UNSIGNED);

/*	RESERVED_12 RRRR1111-->00001111	*/
ChipAddReg(hChip,R_RESERVED_12,"RESERVED_12",0x0087,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_12,AGC_VAL_HI,"AGC_VAL_HI",0,4,CHIP_UNSIGNED);

/*	AGC_TARGET 00000000	*/
ChipAddReg(hChip,R_AGC_TARGET,"AGC_TARGET",0x0088,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC_TARGET,AGC_TARGET,"AGC_TARGET",0,8,CHIP_UNSIGNED);

/*	AGC_GAIN1 00000000	*/
ChipAddReg(hChip,R_AGC_GAIN1,"AGC_GAIN1",0x0089,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC_GAIN1,AGC_GAIN_LO,"AGC_GAIN_LO",0,8,CHIP_UNSIGNED);

/*	AGC_GAIN2 RRR10000-->00010000	*/
ChipAddReg(hChip,R_AGC_GAIN2,"AGC_GAIN2",0x008a,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_AGC_GAIN2,AGC_LOCKED_GAIN2,"AGC_LOCKED_GAIN2",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_AGC_GAIN2,AGC_GAIN_HI,"AGC_GAIN_HI",0,4,CHIP_UNSIGNED);

/*	RESERVED_13 RRRRRRR1-->00000001	*/
ChipAddReg(hChip,R_RESERVED_13,"RESERVED_13",0x008b,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_13,ITB_INVERT,"ITB_INVERT",0,1,CHIP_UNSIGNED);

/*	RESERVED_14 00000000	*/
ChipAddReg(hChip,R_RESERVED_14,"RESERVED_14",0x008c,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_14,ITB_FREQ_LO,"ITB_FREQ_LO",0,8,CHIP_UNSIGNED);

/*	RESERVED_15 RR111111-->00111111	*/
ChipAddReg(hChip,R_RESERVED_15,"RESERVED_15",0x008d,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_15,ITB_FREQ_HI,"ITB_FREQ_HI",0,6,CHIP_UNSIGNED);

/*	CAS_CTL	 01011000*/
ChipAddReg(hChip,R_CAS_CTL,"CAS_CTL",0x008e,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CAS_CTL,CCS_ENABLE,"CCS_ENABLE",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_CAS_CTL,ACS_DISABLE,"ACS_DISABLE",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_CAS_CTL,DAGC_DIS,"DAGC_DIS",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_CAS_CTL,DAGC_GAIN,"DAGC_GAIN",3,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_CAS_CTL,CCSMU,"CCSMU",0,3,CHIP_UNSIGNED);

/*	CAS_FREQ 00000000	*/
ChipAddReg(hChip,R_CAS_FREQ,"CAS_FREQ",0x008f,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CAS_FREQ,CCS_FREQ,"CCS_FREQ",0,8,CHIP_UNSIGNED);

/*	CAS_DAGCGAIN 00000000	*/
ChipAddReg(hChip,R_CAS_DAGCGAIN,"CAS_DAGCGAIN",0x0090,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CAS_DAGCGAIN,CAS_DAGC_GAIN,"CAS_DAGC_GAIN",0,8,CHIP_UNSIGNED);

/*	SYR_CTL 01111010	*/
ChipAddReg(hChip,R_SYR_CTL,"SYR_CTL",0x0091,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_SYR_CTL,SICTHENABLE,"SICTH_ENABLE",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_SYR_CTL,LONG_ECHO,"LONG_ECHO",3,4,CHIP_UNSIGNED);
ChipAddField(hChip,R_SYR_CTL,AUTO_LE_EN,"AUTO_LE_EN",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_SYR_CTL,SYR_BYPASS,"SYR_BYPASS",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_SYR_CTL,SYR_TR_DIS,"SYR_TR_DIS",0,1,CHIP_UNSIGNED);

/*	SYR_STAT RRR1R100-->00010100 */
ChipAddReg(hChip,R_SYR_STAT,"SYR_STAT",0x0092,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_SYR_STAT,SYR_LOCKED_STAT,"SYR_LOCKED_STAT",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_SYR_STAT,SYR_MODE,"SYR_MODE",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_SYR_STAT,SYR_GUARD,"SYR_GUARD",0,2,CHIP_UNSIGNED);

/*	RESERVED_16 00000000	*/
ChipAddReg(hChip,R_RESERVED_16,"RESERVED_16",0x0093,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_16,SYR_NCO_LO,"SYR_NCO_LO",0,8,CHIP_UNSIGNED);

/*	RESERVED_17 RR111111-->00111111	*/
ChipAddReg(hChip,R_RESERVED_17,"RESERVED_17",0x0094,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_17,SYR_NCO_HI,"SYR_NCO_HI",0,6,CHIP_UNSIGNED);

/*	SYR_OFFSET1 00000000	*/
ChipAddReg(hChip,R_SYR_OFFSET1,"SYR_OFFSET1",0x0095,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_SYR_OFFSET1,SYR_OFFSET_LO,"SYR_OFFSET_LO",0,8,CHIP_UNSIGNED);

/*	SYR_OFFSET2 RR111111-->00111111*/
ChipAddReg(hChip,R_SYR_OFFSET2,"SYR_OFFSET2",0x0096,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_SYR_OFFSET2,SYR_OFFSET_HI,"SYR_OFFSET_HI",0,6,CHIP_UNSIGNED);

/*	RESERVED_18 RRR11010-->00011010	*/
ChipAddReg(hChip,R_RESERVED_18,"RESERVED_18",0x0097,*DefVal++,STCHIP_ACCESS_WR);
/*Fiel for 360_E*/
ChipAddField(hChip,R_RESERVED_18,SHIFT_FFT_TRIG,"SHIFT_FFT_TRIG",3,2,CHIP_UNSIGNED);
/****************/
ChipAddField(hChip,R_RESERVED_18,FFT_TRIGGER,"FFT_TRIGGER",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_18,FFT_MANUAL,"FFT_MANUAL",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_18,IFFT_MODE,"IFFT_MODE",0,1,CHIP_UNSIGNED);

/*	SCR_CTL	R111RR10-->01110010*/
ChipAddReg(hChip,R_SCR_CTL,"SCR_CTL",0x0098,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_SCR_CTL,SYRADJDECAY,"SYRADJDECAY",4,3,CHIP_UNSIGNED);
ChipAddField(hChip,R_SCR_CTL,SCR_CPEDIS,"SCR_CPEDIS",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_SCR_CTL,SCR_DIS,"SCR_DIS",0,1,CHIP_UNSIGNED);

/*	PPM_CTL1 01001010	*/
ChipAddReg(hChip,R_PPM_CTL1,"PPM_CTL1",0x0099,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_PPM_CTL1,MEAN_OFF,"MEAN_OFF",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_PPM_CTL1,GRAD_OFF,"GRAD_OFF",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_PPM_CTL1,PPM_MAXFREQ,"PPM_MAXFREQ",4,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_PPM_CTL1,PPM_MAXTIM,"PPM_MAXTIM",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_PPM_CTL1,PPM_INVSEL,"PPM_INVSEL",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_PPM_CTL1,PPM_SCATDIS,"PPM_SCATDIS",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_PPM_CTL1,PPM_BYP,"PPM_BYP",0,1,CHIP_UNSIGNED);

/*	TRL_CTL	01111000*/
ChipAddReg(hChip,R_TRL_CTL,"TRL_CTL",0x009a,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TRL_CTL,TRL_NOMRATE_LSB,"TRL_NOMRATE_LSB",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TRL_CTL,TRL_GAIN_FACTOR,"TRL_GAIN_FACTOR",3,4,CHIP_UNSIGNED);
ChipAddField(hChip,R_TRL_CTL,TRL_LOOPGAIN,"TRL_LOOPGAIN",0,3,CHIP_UNSIGNED);

/*	TRL_NOMRATE1 00000000	*/
ChipAddReg(hChip,R_TRL_NOMRATE1,"TRL_NOMRATE1",0x009b,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TRL_NOMRATE1,TRL_NOMRATE_LO,"TRL_NOMRATE_LO",0,8,CHIP_UNSIGNED);

/*	TRL_NOMRATE2 00000000	*/
ChipAddReg(hChip,R_TRL_NOMRATE2,"TRL_NOMRATE2",0x009c,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TRL_NOMRATE2,TRL_NOMRATE_HI,"TRL_NOMRATE_HI",0,8,CHIP_UNSIGNED);

/*	TRL_TIME1 00000000	*/
ChipAddReg(hChip,R_TRL_TIME1,"TRL_TIME1",0x009d,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TRL_TIME1,TRL_TOFFSET_LO,"TRL_TOFFSET_LO",0,8,CHIP_UNSIGNED);

/*	TRL_TIME2 00000000	*/
ChipAddReg(hChip,R_TRL_TIME2,"TRL_TIME2",0x009e,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TRL_TIME2,TRL_TOFFSET_HI,"TRL_TOFFSET_HI",0,8,CHIP_UNSIGNED);

/*	CRL_CTL 01111000	*/
ChipAddReg(hChip,R_CRL_CTL,"CRL_CTL",0x009f,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CRL_CTL,CRL_DIS,"CRL_DIS",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_CRL_CTL,CRL_GAIN_FACTOR,"CRL_GAIN_FACTOR",3,4,CHIP_UNSIGNED);
ChipAddField(hChip,R_CRL_CTL,CRL_LOOPGAIN,"CRL_LOOPGAIN",0,3,CHIP_UNSIGNED);

/*	CRL_FREQ1 00000000	*/
ChipAddReg(hChip,R_CRL_FREQ1,"CRL_FREQ1",0x00a0,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CRL_FREQ1,CRL_FOFFSET_LO,"CRL_FOFFSET_LO",0,8,CHIP_UNSIGNED);

/*	CRL_FREQ2 00000000	*/
ChipAddReg(hChip,R_CRL_FREQ2,"CRL_FREQ2",0x00a1,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CRL_FREQ2,CRL_FOFFSET_HI,"CRL_FOFFSET_HI",0,8,CHIP_UNSIGNED);

/*	CRL_FREQ3 01111111	*/
ChipAddReg(hChip,R_CRL_FREQ3,"CRL_FREQ3",0x00a2,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CRL_FREQ3,SEXT,"SEXT",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_CRL_FREQ3,CRL_FOFFSET_VHI,"CRL_FOFFSET_VHI",0,7,CHIP_UNSIGNED);

/*	CHC_CTL1 00010101	*/
ChipAddReg(hChip,R_CHC_CTL1,"CHC_CTL1",0x00a3,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CHC_CTL1,MEAN_PILOT_GAIN,"MEAN_PILOT_GAIN",5,3,CHIP_UNSIGNED);
ChipAddField(hChip,R_CHC_CTL1,MANMEANP,"MANMEANP",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_CHC_CTL1,DBADP,"DBADP",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_CHC_CTL1,DNOISEN,"DNOISEN",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_CHC_CTL1,DCHCPRED,"DCHCPRED",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_CHC_CTL1,CHC_INT,"CHC_INT",0,1,CHIP_UNSIGNED);

/*	CHC_SNR 00000000	*/
ChipAddReg(hChip,R_CHC_SNR,"CHC_SNR",0x00a4,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CHC_SNR,CHC_SNR,"CHC_SNR",0,8,CHIP_UNSIGNED);

/*	BDI_CTL	RRRRRR10-->00000010*/
ChipAddReg(hChip,R_BDI_CTL,"BDI_CTL",0x00a5,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_BDI_CTL,BDI_LPSEL,"BDI_LPSEL",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_BDI_CTL,BDI_SERIAL,"BDI_SERIAL",0,1,CHIP_UNSIGNED);

/*	DMP_CTL	RRR11110-->00011110*/
ChipAddReg(hChip,R_DMP_CTL,"DMP_CTL",0x00a6,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_DMP_CTL,DMP_SCALING_FACTOR,"DMP_SCALING_FACTOR",1,4,CHIP_UNSIGNED);
ChipAddField(hChip,R_DMP_CTL,DMP_SDDIS,"DMP_SDDIS",0,1,CHIP_UNSIGNED);

/*	TPS_RCVD1 R101RR11-->01010011	*/
ChipAddReg(hChip,R_TPS_RCVD1,"TPS_RCVD1",0x00a7,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TPS_RCVD1,TPS_CHANGE,"TPS_CHANGE",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TPS_RCVD1,BCH_OK,"BCH_OK",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TPS_RCVD1,TPS_SYNC,"TPS_SYNC",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TPS_RCVD1,TPS_FRAME,"TPS_FRAME",0,2,CHIP_UNSIGNED);

/*	TPS_RCVD2 R111RR11-->01110011	*/
ChipAddReg(hChip,R_TPS_RCVD2,"TPS_RCVD2",0x00a8,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TPS_RCVD2,TPS_HIERMODE,"TPS_HIERMODE",4,3,CHIP_UNSIGNED);
ChipAddField(hChip,R_TPS_RCVD2,TPS_CONST,"TPS_CONST",0,2,CHIP_UNSIGNED);

/*	TPS_RCVD3 R111R111-->01110111	*/
ChipAddReg(hChip,R_TPS_RCVD3,"TPS_RCVD3",0x00a9,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TPS_RCVD3,TPS_LPCODE,"TPS_LPCODE",4,3,CHIP_UNSIGNED);
ChipAddField(hChip,R_TPS_RCVD3,TPS_HPCODE,"TPS_HPCODE",0,3,CHIP_UNSIGNED);

/*	TPS_RCVD4 RR11RR11-->00110011	*/
ChipAddReg(hChip,R_TPS_RCVD4,"TPS_RCVD4",0x00aa,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TPS_RCVD4,TPS_GUARD,"TPS_GUARD",4,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_TPS_RCVD4,TPS_MODE,"TPS_MODE",0,2,CHIP_UNSIGNED);

/*	TPS_ID_CELL1 00000000	*/
ChipAddReg(hChip,R_TPS_ID_CELL1,"TPS_ID_CELL1",0x00ab,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TPS_ID_CELL1,TPS_ID_CELL_LO,"TPS_ID_CELL_LO",0,8,CHIP_UNSIGNED);

/*	TPS_ID_CELL2 00000000	*/
ChipAddReg(hChip,R_TPS_ID_CELL2,"TPS_ID_CELL2",0x00ac,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TPS_ID_CELL2,TPS_ID_CELL_HI,"TPS_ID_CELL_HI",0,8,CHIP_UNSIGNED);

/*	RESERVED_19 00000011	*/
ChipAddReg(hChip,R_RESERVED_19,"RESERVED_19",0x00ad,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_19,TPS_NA,"TPS_NA",2,6,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_19,TPS_SETFRAME,"TPS_SETFRAME",0,2,CHIP_UNSIGNED);

/*	RESERVED_20 R111RR11-->01110011	*/
ChipAddReg(hChip,R_RESERVED_20,"RESERVED_20",0x00ae,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_20,TPS_SETHIERMODE,"TPS_SETHIERMODE",4,3,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_20,TPS_SETCONST,"TPS_SETCONST",0,2,CHIP_UNSIGNED);

/*	RESERVED_21 R111R111-->01110111	*/
ChipAddReg(hChip,R_RESERVED_21,"RESERVED_21",0x00af,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_21,TPS_SETLPCODE,"TPS_SETLPCODE",4,3,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_21,TPS_SETHPCODE,"TPS_SETHPCODE",0,3,CHIP_UNSIGNED);

/*	TPS_CTL	RRRRR101-->00000101*/
ChipAddReg(hChip,R_TPS_CTL,"TPS_CTL",0x00b0,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TPS_CTL,TPS_IMM,"TPS_IMM",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TPS_CTL,TPS_BCHDIS,"TPS_BCHDIS",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TPS_CTL,TPS_UPDDIS,"TPS_UPDDIS",0,1,CHIP_UNSIGNED);

/*	CTL_FFTOSNUM R1111111-->01111111*/
ChipAddReg(hChip,R_CTL_FFTOSNUM,"CTL_FFTOSNUM",0x00b1,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CTL_FFTOSNUM,SYMBOL_NUMBER,"SYMBOL_NUMBER",0,7,CHIP_UNSIGNED);

/*	TESTSELECT RRR11111-->00011111	*/
ChipAddReg(hChip,R_TESTSELECT,"TESTSELECT",0x00b2,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TESTSELECT,TESTSELECT,"TESTSELECT",0,5,CHIP_UNSIGNED);

/*	MSC_REV 00000000*/
ChipAddReg(hChip,R_MSC_REV,"MSC_REV",0x00b3,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_MSC_REV,REV_NUMBER,"REV_NUMBER",0,8,CHIP_UNSIGNED);

/*	PIR_CTL	RRRRRRR1-->00000001*/
ChipAddReg(hChip,R_PIR_CTL,"PIR_CTL",0x00b4,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_PIR_CTL,FREEZE,"FREEZE",0,1,CHIP_UNSIGNED);

/*	SNR_CARRIER1 00000000	*/
ChipAddReg(hChip,R_SNR_CARRIER1,"SNR_CARRIER1",0x00b5,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_SNR_CARRIER1,SNR_CARRIER_LO,"SNR_CARRIER_LO",0,8,CHIP_UNSIGNED);

/*	SNR_CARRIER2 0RR00000-->01100000	*/
ChipAddReg(hChip,R_SNR_CARRIER2,"SNR_CARRIER2",0x00b6,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_SNR_CARRIER2,MEAN,"MEAN",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_SNR_CARRIER2,SNR_CARRIER_HI,"SNR_CARRIER_HI",0,5,CHIP_UNSIGNED);

/*	RESERVED_22 00000000	*/
ChipAddReg(hChip,R_RESERVED_22,"RESERVED_22",0x00b7,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_22,PPM_CPC,"PPM_CPC",0,8,CHIP_UNSIGNED);

/*	RESERVED_23 00000000	*/
ChipAddReg(hChip,R_RESERVED_23,"RESERVED_23",0x00b8,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_23,ADDRESS_BYTE_0,"ADDRESS_BYTE_0",0,8,CHIP_UNSIGNED);

/*	RESERVED_24 00000000	*/
ChipAddReg(hChip,R_RESERVED_24,"RESERVED_24",0x00b9,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_24,ADDRESS_BYTE_1,"ADDRESS_BYTE_1",0,8,CHIP_UNSIGNED);

/*	RESERVED_25 00000000	*/
ChipAddReg(hChip,R_RESERVED_25,"RESERVED_25",0x00ba,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_25,DATA_BYTE_0,"DATA_BYTE_0",0,8,CHIP_UNSIGNED);

/*	RESERVED_26 00000000	*/
ChipAddReg(hChip,R_RESERVED_26,"RESERVED_26",0x00bb,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_26,DATA_BYTE_1,"DATA_BYTE_1",0,8,CHIP_UNSIGNED);

/*	RESERVED_27 00000000	*/
ChipAddReg(hChip,R_RESERVED_27,"RESERVED_27",0x00bc,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_27,DATA_BYTE_2,"DATA_BYTE_2",0,8,CHIP_UNSIGNED);

/*	RESERVED_28 00000000	*/
ChipAddReg(hChip,R_RESERVED_28,"RESERVED_28",0x00bd,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_28,DATA_BYTE_3,"DATA_BYTE_3",0,8,CHIP_UNSIGNED);

/*	RESERVED_29 RRRRRRRR-->00000000	*/
ChipAddReg(hChip,R_RESERVED_29,"RESERVED_29",0x00be,*DefVal++,STCHIP_ACCESS_WR);

/*	RESERVED_30 00000000	*/
ChipAddReg(hChip,R_RESERVED_30,"RESERVED_30",0x00bf,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_30,MEM_SELECT_BYTE,"MEM_SELECT_BYTE",0,8,CHIP_UNSIGNED);


/*	RESERVED_31 0000R010-->00001010*/
ChipAddReg(hChip,R_RESERVED_31,"RESERVED_31",0x0040,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_31,FEC_MODE,"FEC_MODE",4,4,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_31,VIT_DIFF,"VIT_DIFF",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_31,SYNC,"SYNC",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_31,SYM,"SYM",0,1,CHIP_UNSIGNED);

/*	VTH0 R1111111-->01111111*/
ChipAddReg(hChip,R_VTH0,"VTH0",0x0041,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_VTH0,VTH0,"VTH0",0,7,CHIP_UNSIGNED);

/*	VTH1	R1111111-->01111111*/
ChipAddReg(hChip,R_VTH1,"VTH1",0x0042,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_VTH1,VTH1,"VTH1",0,7,CHIP_UNSIGNED);

/*	VTH2	R1111111-->01111111*/
ChipAddReg(hChip,R_VTH2,"VTH2",0x0043,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_VTH2,VTH2,"VTH2",0,7,CHIP_UNSIGNED);

/*	VTH3	R1111111-->01111111*/
ChipAddReg(hChip,R_VTH3,"VTH3",0x0044,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_VTH3,VTH3,"VTH3",0,7,CHIP_UNSIGNED);

/*	RESERVED_32	R1111111-->01111111*/
ChipAddReg(hChip,R_RESERVED_32,"RESERVED_32",0x0045,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_32,VTH4,"VTH4",0,7,CHIP_UNSIGNED);

/*	VTH5	R1111111-->01111111*/
ChipAddReg(hChip,R_VTH5,"VTH5",0x0046,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_VTH5,VTH5,"VTH5",0,7,CHIP_UNSIGNED);

/*	RESERVED_33	RRRRRRRR-->00000000*/
ChipAddReg(hChip,R_RESERVED_33,"RESERVED_33",0x0047,*DefVal++,STCHIP_ACCESS_WR);

/*	VITPROG 0011RR11-->00110011*/
ChipAddReg(hChip,R_VITPROG,"VITPROG",0x0049,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_VITPROG,FORCE_ROTA,"FORCE_ROTA",6,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_VITPROG,AUTO_FREEZE,"AUTO_FREEZE",4,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_VITPROG,MDIVIDER,"MDIVIDER",0,2,CHIP_UNSIGNED);

/*	PR 0R010101-->01010101	*/
ChipAddReg(hChip,R_PR,"PR",0x004a,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_PR,FRAPTCR,"FRAPTCR",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_PR,E7_8,"E7_8",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_PR,E6_7,"E6_7",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_PR,E5_6,"E5_6",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_PR,E3_4,"E3_4",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_PR,E2_3,"E2_3",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_PR,E1_2,"E1_2",0,1,CHIP_UNSIGNED);

/*	VSEARCH	01001100*/
ChipAddReg(hChip,R_VSEARCH,"VSEARCH",0x004b,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_VSEARCH,PR_AUTO,"PR_AUTO",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_VSEARCH,PR_FREEZE,"PR_FREEZE",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_VSEARCH,SAMPNUM,"SAMPNUM",4,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_VSEARCH,TIMEOUT,"TIMEOUT",2,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_VSEARCH,HYSTER,"HYSTER",0,2,CHIP_UNSIGNED);

/*	RS	01010101*/
ChipAddReg(hChip,R_RS,"RS",0x004c,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RS,DEINT_ENA,"DEINT_ENA",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RS,OUTRS_SP,"OUTRS_SP",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RS,RS_ENA,"RS_ENA",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RS,DESCR_ENA,"DESCR_ENA",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RS,ERRBIT_ENA,"ERRBIT_ENA",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RS,FORCE47,"FORCE47",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RS,CLK_POL,"CLK_POL",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RS,CLK_CFG,"CLK_CFG",0,1,CHIP_UNSIGNED);

/*	RSOUT	RRR10000-->00010000*/
ChipAddReg(hChip,R_RSOUT,"RSOUT",0x004d,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RSOUT,ENA_STBACKEND,"ENA_STBACKEND",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RSOUT,ENA8_LEVEL,"ENA8_LEVEL",0,4,CHIP_UNSIGNED);

/*	ERRCTRL1 0100R011-->01001011*/
ChipAddReg(hChip,R_ERRCTRL1,"ERRCTRL1",0x004e,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ERRCTRL1,ERRMODE1,"ERRMODE1",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ERRCTRL1,TESTERS1,"TESTERS1",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ERRCTRL1,ERR_SOURCE1,"ERR_SOURCE1",4,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_ERRCTRL1,RESET_CNTR1,"RESET_CNTR1",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ERRCTRL1,NUM_EVENT1,"NUM_EVENT1",0,2,CHIP_UNSIGNED);

/*	ERRCNTM1 00000000*/
ChipAddReg(hChip,R_ERRCNTM1,"ERRCNTM1",0x004f,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ERRCNTM1,ERROR_COUNT1_HI,"ERROR_COUNT1_HI",0,8,CHIP_UNSIGNED);

/*	ERRCNTL1 00000000	*/
ChipAddReg(hChip,R_ERRCNTL1,"ERRCNTL1",0x0050,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ERRCNTL1,ERROR_COUNT1_LO,"ERROR_COUNT1_LO",0,8,CHIP_UNSIGNED);

/*	ERRCTRL2 0100R011-->01001011*/
ChipAddReg(hChip,R_ERRCTRL2,"ERRCTRL2",0x0051,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ERRCTRL2,ERRMODE2,"ERRMODE2",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ERRCTRL2,TESTERS2,"TESTERS2",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ERRCTRL2,ERR_SOURCE2,"ERR_SOURCE2",4,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_ERRCTRL2,RESET_CNTR2,"RESET_CNTR2",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ERRCTRL2,NUM_EVENT2,"NUM_EVENT2",0,2,CHIP_UNSIGNED);

/*	ERRCNTM2 00000000 */
ChipAddReg(hChip,R_ERRCNTM2,"ERRCNTM2",0x0052,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ERRCNTM2,ERROR_COUNT2_HI,"ERROR_COUNT2_HI",0,8,CHIP_UNSIGNED);

/*	ERRCNTL2 00000000*/
ChipAddReg(hChip,R_ERRCNTL2,"ERRCNTL2",0x0053,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ERRCNTL2,ERROR_COUNT2_LO,"ERROR_COUNT2_LO",0,8,CHIP_UNSIGNED);

/*	RESERVED_34 RRRRRRRR-->00000000	*/
ChipAddReg(hChip,R_RESERVED_34,"RESERVED_34",0x0054,*DefVal++,STCHIP_ACCESS_WR);

/*	VERROR	00000000*/
ChipAddReg(hChip,R_VERROR,"VERROR",0x0055,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_VERROR,ERROR_VALUE,"ERROR_VALUE",0,8,CHIP_UNSIGNED);

/*	ERRCTRL3 0100R011-->01001011*/
ChipAddReg(hChip,R_ERRCTRL3,"ERRCTRL3",0x0056,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ERRCTRL3,ERRMODE3,"ERRMODE3",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ERRCTRL3,TESTERS3,"TESTERS3",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ERRCTRL3,ERR_SOURCE3,"ERR_SOURCE3",4,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_ERRCTRL3,RESET_CNTR3,"RESET_CNTR3",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ERRCTRL3,NUM_EVENT3,"NUM_EVENT3",0,2,CHIP_UNSIGNED);

/*	ERRCNTM3 00000000*/
ChipAddReg(hChip,R_ERRCNTM3,"ERRCNTM3",0x0057,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ERRCNTM3,ERROR_COUNT3_HI,"ERROR_COUNT3_HI",0,8,CHIP_UNSIGNED);

/*	ERRCNTL3 00000000*/
ChipAddReg(hChip,R_ERRCNTL3,"ERRCNTL3",0x0058,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ERRCNTL3,ERROR_COUNT3_LO,"ERROR_COUNT3_LO",0,8,CHIP_UNSIGNED);

/*	RESERVED_35 00000000*/
ChipAddReg(hChip,R_RESERVED_35,"RESERVED_35",0x0059,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_35,DILSTK_HI,"DILSTK_HI",0,8,CHIP_UNSIGNED);

/*	RESERVED_36 00000000	*/
ChipAddReg(hChip,R_RESERVED_36,"RESERVED_36",0x005a,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_36,DILSTK_LO,"DILSTK_LO",0,8,CHIP_UNSIGNED);

/*	RESERVED_37 RRRRRRRR-->00000000	*/
ChipAddReg(hChip,R_RESERVED_37,"RESERVED_37",0x005b,*DefVal++,STCHIP_ACCESS_WR);

/*	RESERVED_38 RRRRRRRR-->00000000	*/
ChipAddReg(hChip,R_RESERVED_38,"RESERVED_38",0x005c,*DefVal++,STCHIP_ACCESS_WR);

/*	LNBRX	01RR1000-->01001000*/
ChipAddReg(hChip,R_LNBRX,"LNBRX",0x005d,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_LNBRX,LINE_OK,"LINE_OK",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_LNBRX,OCCURRED_ERR,"OCCURRED_ERR",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_LNBRX,RSOV_DATAIN,"RSOV_DATAIN",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_LNBRX,LNBTX_CHIPADDR,"LNBTX_CHIPADDR",0,3,CHIP_UNSIGNED);

/*	RESERVED_39 0101R101-->01010101*/
ChipAddReg(hChip,R_RESERVED_39,"RESERVED_39",0x005e,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_39,DEINTTC,"DEINTTC",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_39,DIL64_ON,"DIL64_ON",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_39,RSTC,"RSTC",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_39,DESCRAMTC,"DESCRAMTC",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_39,MODSYNCBYT,"MODSYNCBYT",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_39,LOWP_DIS,"LOWP_DIS",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_39,HIGHP_DIS,"HIGHP_DIS",0,1,CHIP_UNSIGNED);

/*	RESERVED_40 R1000111-->01000111	*/
ChipAddReg(hChip,R_RESERVED_40,"RESERVED_40",0x005f,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_40,RAND_RAMP,"RAND_RAMP",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_40,NOISE_LEVEL,"NOISE_LEVEL",3,3,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_40,PR_VIT_BIST,"PR_VIT_BIST",0,3,CHIP_UNSIGNED);

/*	RESERVED_41 01010101	*/
ChipAddReg(hChip,R_RESERVED_41,"RESERVED_41",0x00c0,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_41,FRES_DISPLAY,"FRES_DISPLAY",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_41,FRESRS,"FRESRS",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_41,FRESACS,"FRESACS",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_41,FRES_PRIF,"FRES_PRIF",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_41,FRESFEC1_2,"FRESFEC1_2",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_41,FRESFEC,"FRESFEC",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_41,FRESCORE1_2,"FRESCORE1_2",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_41,FRESCORE,"FRESCORE",0,1,CHIP_UNSIGNED);

/*	ANACTRL	01010101*/
ChipAddReg(hChip,R_ANACTRL,"ANACTRL",0x00c1,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ANACTRL,STDBY_PLL2X4,"STDBY_PLL2X4",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ANACTRL,BYPASS_XTAL,"BYPASS_XTAL",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ANACTRL,STDBY_BUFFER,"STDBY_BUFFER",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ANACTRL,STDBY_BIAS,"STDBY_BIAS",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ANACTRL,STDBY_ADPIPE,"STDBY_ADPIPE",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ANACTRL,BYPASS_PLL,"BYPASS_PLL",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ANACTRL,DIS_PAD_OSC,"DIS_PAD_OSC",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ANACTRL,STDBY_PLLXN,"STDBY_PLLXN",0,1,CHIP_UNSIGNED);

/*	RESERVED_42 01000111	*/
ChipAddReg(hChip,R_RESERVED_42,"RESERVED_42",0x00c2,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_42,EXT_TESTIN,"EXT_TESTIN",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_42,EXT_ADC,"EXT_ADC",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_42,TEST_IN,"TEST_IN",3,3,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_42,TS,"TS",0,3,CHIP_UNSIGNED);

/*	RESERVED_43 0RRR0101-->01110101	*/
ChipAddReg(hChip,R_RESERVED_43,"RESERVED_43",0x00c3,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_43,CKFECEXT,"CKFECEXT",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_43,FORCERATE1,"FORCERATE1",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_43,TSTCKRS,"TSTCKRS",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_43,TSTCKDIL,"TSTCKDIL",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_43,DIRCKINT,"DIRCKINT",0,1,CHIP_UNSIGNED);

/*	RESERVED_44 0110R000-->01101000	*/
ChipAddReg(hChip,R_RESERVED_44,"RESERVED_44",0x00c4,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_44,EN_VI2C,"EN_VI2C",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_44,TI2C,"TI2C",5,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_44,BFAIL_BAD,"BFAIL_BAD",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_44,TST_PRIF,"TST_PRIF",0,3,CHIP_UNSIGNED);

/*	RESERVED_45 01011100	*/
ChipAddReg(hChip,R_RESERVED_45,"RESERVED_45",0x00c5,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_45,SELADR1,"SELADR1",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_45,FSELRAM1,"FSELRAM1",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_45,FSELDEC,"FSELDEC",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_45,FOEB,"FOEB",2,3,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_45,FADR,"FADR",0,2,CHIP_UNSIGNED);

/*	RESERVED_46 0RR01000-->01101000	*/
ChipAddReg(hChip,R_RESERVED_46,"RESERVED_46",0x00c6,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_46,FORCEPHA,"FORCEPHA",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_46,FNEWPHA,"FNEWPHA",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_46,FROT90,"FROT90",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_46,FR,"FR",0,3,CHIP_UNSIGNED);

/*	RESERVED_47 01010101	*/
ChipAddReg(hChip,R_RESERVED_47,"RESERVED_47",0x00c7,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_47,EN_VLOG,"EN_VLOG",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_47,SELVIT60,"SELVIT60",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_47,SELSYN3,"SELSYN3",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_47,SELSYN2,"SELSYN2",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_47,SELSYN1,"SELSYN1",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_47,SELLIFO,"SELLIFO",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_47,SELFIFO,"SELFIFO",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_47,TSTFIFO,"TSTFIFO",0,1,CHIP_UNSIGNED);

/*	RESERVED_48 01010101*/
ChipAddReg(hChip,R_RESERVED_48,"RESERVED_48",0x00c8,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_48,SEL_VITDATAIN,"SEL_VITDATAIN",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_48,FORCE_ACS,"FORCE_ACS",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_48,TSTSYN,"TSTSYN",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_48,TSTRAM64,"TSTRAM64",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_48,TSTRAM,"TSTRAM",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_48,TSTERR2,"TSTERR2",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_48,TSTERR,"TSTERR",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_48,TSTACS,"TSTACS",0,1,CHIP_UNSIGNED);

/*	RESERVED_49 RRRRR101-->00000101	*/
ChipAddReg(hChip,R_RESERVED_49,"RESERVED_49",0x00c9,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_49,FORMSB,"FORMSB",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_49,FORLSB,"FORLSB",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_49,TSTFIFO_TSTFIFO,"TSTFIFO_TSTFIFO",0,1,CHIP_UNSIGNED);

/*	RESERVED_50 01001101	*/
ChipAddReg(hChip,R_RESERVED_50,"RESERVED_50",0x00ca,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_50,TST_SCRA,"TST_SCRA",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_50,OLDRS6,"OLDRS6",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_50,ADCT,"ADCT",4,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_50,DILT,"DILT",2,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_50,SCARBIT,"SCARBIT",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_50,TSTRS_EN,"TSTRS_EN",0,1,CHIP_UNSIGNED);

/*	CONSTMODE RRR11011-->00011011	*/
ChipAddReg(hChip,R_CONSTMODE,"CONSTMODE",0x00cb,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CONSTMODE,CAR_TYPE,"CAR_TYPE",3,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_CONSTMODE,IQ_RANGE,"IQ_RANGE",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_CONSTMODE,CONST_MODE,"CONST_MODE",0,2,CHIP_UNSIGNED);

/*	CONSTCARR1 00000000	*/
ChipAddReg(hChip,R_CONSTCARR1,"CONSTCARR1",0x00cc,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CONSTCARR1,CONST_CARR_LO,"CONST_CARR_LO",0,8,CHIP_UNSIGNED);

/*	CONSTCARR2 RRR11111-->00011111	*/
ChipAddReg(hChip,R_CONSTCARR2,"CONSTCARR2",0x00cd,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_CONSTCARR2,CONST_CARR_HI,"CONST_CARR_HI",0,5,CHIP_UNSIGNED);

/*	ICONSTEL 00000000	*/
ChipAddReg(hChip,R_ICONSTEL,"ICONSTEL",0x00ce,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ICONSTEL,ICONSTEL,"ICONSTEL",0,8,CHIP_UNSIGNED);

/*	QCONSTEL 00000000	*/
ChipAddReg(hChip,R_QCONSTEL,"QCONSTEL",0x00cf,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_QCONSTEL,QCONSTEL,"QCONSTEL",0,8,CHIP_UNSIGNED);

/*	RESERVED_51 01010101	*/
ChipAddReg(hChip,R_RESERVED_51,"RESERVED_51",0x00d0,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_51,BEND_BDI,"BEND_BDI",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_51,BBAD_BDI,"BBAD_BDI",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_51,BEND_PPM,"BEND_PPM",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_51,BBAD_PPM,"BBAD_PPM",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_51,BEND_SDI,"BEND_SDI",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_51,BBAD_SDI,"BBAD_SDI",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_51,BEND_INS,"BEND_INS",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_51,BBAD_INS,"BBAD_INS",0,1,CHIP_UNSIGNED);

/*	RESERVED_52 01010101*/
ChipAddReg(hChip,R_RESERVED_52,"RESERVED_52",0x00d1,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_52,BEND_CHC2B,"BEND_CHC2B",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_52,BBAD_CHC2B,"BBAD_CHC2B",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_52,BEND_CHC3,"BEND_CHC3",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_52,BBAD_CHC3,"BBAD_CHC3",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_52,BEND_FFTI,"BEND_FFTI",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_52,BBAD_FFTI,"BBAD_FFTI",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_52,BEND_FFTW,"BEND_FFTW",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_52,BBAD_FFTW,"BBAD_FFTW",0,1,CHIP_UNSIGNED);

/*	RESERVED_53 01010101	*/
ChipAddReg(hChip,R_RESERVED_53,"RESERVED_53",0x00d2,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_53,BEND_RS,"BEND_RS",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_53,BBAD_RS,"BBAD_RS",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_53,BEND_SYR,"BEND_SYR",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_53,BBAD_SYR,"BBAD_SYR",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_53,BEND_CHC1,"BEND_CHC1",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_53,BBAD_CHC1,"BBAD_CHC1",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_53,BEND_CHC2,"BEND_CHC2",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_53,BBAD_CHC2,"BBAD_CHC2",0,1,CHIP_UNSIGNED);

/*	RESERVED_54 01010101	*/
ChipAddReg(hChip,R_RESERVED_54,"RESERVED_54",0x00d3,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_54,BEND_FIFO,"BEND_FIFO",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_54,BBAD_FIFO,"BBAD_FIFO",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_54,BEND_VIT2,"BEND_VIT2",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_54,BBAD_VIT2,"BBAD_VIT2",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_54,BEND_VIT1,"BEND_VIT1",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_54,BBAD_VIT1,"BBAD_VIT1",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_54,BEND_DIL,"BEND_DIL",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RESERVED_54,BBAD_DIL,"BBAD_DIL",0,1,CHIP_UNSIGNED);


/*	RF_AGC1 00000000	*/
ChipAddReg(hChip,R_RF_AGC1,"RF_AGC1",0x00d4,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RF_AGC1,RF_AGC1_LEVEL_HI,"RF_AGC1_LEVEL_HI",0,8,CHIP_UNSIGNED);

/*	RF_AGC2	010RR011-->01011011*/
ChipAddReg(hChip,R_RF_AGC2,"RF_AGC2",0x00d5,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RF_AGC2,START_ADC,"START_ADC",7,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RF_AGC2,TEST_ADCGP,"TEST_ADCGP",6,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RF_AGC2,STDBY_ADCGP,"STDBY_ADCGP",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RF_AGC2,ADCGP_OVF,"ADCGP_OVF",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_RF_AGC2,RF_AGC1_LEVEL_LO,"RF_AGC1_LEVEL_LO",0,2,CHIP_UNSIGNED);

/*	RESERVED_55 00000000	*/
ChipAddReg(hChip,R_RESERVED_55,"RESERVED_55",0x00d6,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_RESERVED_55,BUSIN5,"BUSIN5",0,8,CHIP_UNSIGNED);

/*	ANACTRL2 00000000	*/
ChipAddReg(hChip,R_ANACTRL2,"ANACTRL2",0x00db,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ANACTRL2,ANA_CTRL2_BUS,"ANA_CTRL2_BUS",0,8,CHIP_UNSIGNED);

/*	PLLMDIV 00000000	*/
ChipAddReg(hChip,R_PLLMDIV,"PLLMDIV",0x00d8,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_PLLMDIV,PLL_MDIV,"PLL_MDIV",0,8,CHIP_UNSIGNED);

/*	PLLNDIV	00000000*/
ChipAddReg(hChip,R_PLLNDIV,"PLLNDIV",0x00d9,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_PLLNDIV,PLL_NDIV,"PLL_NDIV",0,8,CHIP_UNSIGNED);

/*	PLLSETUP R1110000-->01110000	*/
ChipAddReg(hChip,R_PLLSETUP,"PLLSETUP",0x00da,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_PLLSETUP,PLL_PDIV,"PLL_PDIV",4,3,CHIP_UNSIGNED);
ChipAddField(hChip,R_PLLSETUP,PLL_SETUP,"PLL_SETUP",0,4,CHIP_UNSIGNED);

/*	ANADIGCTRL 00101010	*/
ChipAddReg(hChip,R_ANADIGCTRL,"ANADIGCTRL",0x00d7,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_ANADIGCTRL,BUFFER_INCM,"BUFFER_INCM",6,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_ANADIGCTRL,SEL_CLKDEM,"SEL_CLKDEM",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ANADIGCTRL,SEL_PLL,"SEL_PLL",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ANADIGCTRL,BYPASS_ADC,"BYPASS_ADC",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ANADIGCTRL,ADC_RIS_EGDE,"ADC_RIS_EGDE",2,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ANADIGCTRL,SGN_ADC,"SGN_ADC",1,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_ANADIGCTRL,TEST_ADC,"TEST_ADC",0,1,CHIP_UNSIGNED);

/*	TSTBIST	RR101001-->00101001*/
ChipAddReg(hChip,R_TSTBIST,"TSTBIST",0x00dc,*DefVal++,STCHIP_ACCESS_WR);
ChipAddField(hChip,R_TSTBIST,TST_COLLAR_W,"TST_COLLAR_W",5,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TSTBIST,TST_COLLAR_CS,"TST_COLLAR_CS",4,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TSTBIST,TST_COLLAR,"TST_COLLAR",3,1,CHIP_UNSIGNED);
ChipAddField(hChip,R_TSTBIST,TST_BIST_MODE,"TST_BIST_MODE",1,2,CHIP_UNSIGNED);
ChipAddField(hChip,R_TSTBIST,RBACT,"RBACT",0,1,CHIP_UNSIGNED);




	}
#endif /*#ifndef STTUNER_REG_INIT_OLD_METHOD*/	
/***********Software workaround for good result in STV0361***************/
        while(1)
        {
           count++;
           Error=ChipSetOneRegister(hChip,R_TOPCTRL,0x02);
           if(ChipGetOneRegister(hChip,R_TOPCTRL)==0x02)
           {
             break;
           }
          
        }
        
	ChipApplyDefaultValues(hChip);
	return hChip;
}
