#
# makefile
#
# Copyright (C) STMicroelectronics Ltd. 2002
#
# Makefile for Configs directory
#

RPC_ROOT = ..

include $(RPC_ROOT)/src/mkfiles/host.mak

all:

clean:


DIST_SRC       = makefile \
		 bootstrap.dbg \
		 bootstrap.lku \
		 rpc_mailbox.cfg \
		 rpc_mb282b.cfg \
		 rpc_mb282b_smi.cfg \
		 rpc_mb376.cfg \
                 rpc_mb385.cfg \
                 rpc_mb385_conf.cfg \
                 rpc_mb385_jtag.cfg \
		 rpc_mediaref20.cfg \
		 rpc_mediaref20_clks_2x.cfg \
		 rpc_mediaref20_clks_3.cfg \
		 rpc_mediaref20_smi.cfg \
		 rpc_mediaref40.cfg \
		 rpc_mediaref40.cmd \
                 rpc_nodevice.cfg \
		 rpc_st20.cfg \
		 rpc_st40.cfg \
		 rpc_st40.cmd \
                 st40defs.cmd

include $(RPC_ROOT)/src/mkfiles/install.mak

