#
# makefile
#
# Copyright (C) STMicroelectronics Limited 2003. All rights reserved.
#
# Makefile for rpc runtime harness
#

RPC_ROOT = ../..

DIST_SRC = $(wildcard *.c *.h *.mak) makefile README

all clean :

include $(RPC_ROOT)/src/mkfiles/host.mak
include $(RPC_ROOT)/src/mkfiles/install.mak
