#ifndef _CH_STATUS_H_
#define _CH_STATUS_H_

typedef enum
{
	CH_FAILURE = -1,			/*执行失败，原因不明*/
	CH_SUCCESS = 0,				/*成功*/
	CH_ALLOCMEM_ERROR,			/*内存分配错误*/
	CH_TIMEOUT,					/*超时*/
	CH_NOTRUN,					/*没有运行*/
	CH_INUSE,					/*还在使用中*/
	CH_NULL_POINTER,             /*企图读写空指针*/
	CH_ERROR_PARAM,			/*参数错误*/
	CH_DATE_NOT_ENOUGH,			/* 没有足够的数据*/
	CH_DEQUEUE_OVERFLOW,		/* 队列已满 */   
	CH_ERROR_STACK_OVERFLOW,    /* 栈溢出 */
	CH_ERROR_STACK_EMPTY,		/* 栈空 */
	CH_ERROR_UNEXPECTED,
	CH_ERROR_ABORT,
	CH_ERROR_OUT_OF_MEMORY,
	CH_SINK_FLAG_CAN_INTERRUPT_PARSER,
	CH_HTMLTOKENS_NOT_AN_ENTITY,	
	CH_ERROR_HTMLPARSER_STOPPARSING,/* 停止分析 */
	CH_ERROR_HTMLPARSER_EOF,	/* 流结尾 */
	CH_ERROR_HTMLPARSER_BADTOKENIZER,
	CH_ERROR_HTMLPARSER_BADATTRIBUTE,
	CH_ERROR_HTMLPARSER_INTERRUPTED,
	CH_ERROR_HTMLPARSER_BLOCK,
	CH_ERROR_HTMLPARSER_UNRESOLVEDDTD,
	CH_ERROR_HTMLPARSER_BADURL,
	CH_ERROR_HTMLPARSER_BADCONTEXT,
	CH_ERROR_HTMLPARSER_UNKNOWN,
	CH_ERROR_HTMLPARSER_CANTPROPAGATE,  
	CH_ERROR_HTMLPARSER_CONTEXTMISMATCH,
	CH_ERROR_HTMLPARSER_BADFILENAME,    
	CH_ERROR_HTMLPARSER_INVALIDPARSERCONTEXT,
	CH_ERROR_HTMLPARSER_MISPLACEDTABLECONTENT,
	CH_ERROR_HTMLPARSER_BADDTD,
	CH_ERROR_HTMLPARSER_UNTERMINATEDSTRINGLITERAL,
	CH_ERROR_HTMLPARSER_HIERARCHYTOODEEP,   
	CH_ERROR_NOINTERFACE,
	CH_CONTENT_ATTR_NOT_THERE,
	CH_CONTENT_ATTR_NO_VALUE,
	CH_CONTENT_ATTR_HAS_VALUE,
	
	/* DOM error codes from http://www.w3.org/TR/REC-DOM-Level-1/ */
	CH_ERROR_DOM_START,
	CH_ERROR_DOM_INDEX_SIZE_ERR,			 /*1*/
	CH_ERROR_DOM_DOMSTRING_SIZE_ERR,          /*2*/
	CH_ERROR_DOM_HIERARCHY_REQUEST_ERR,       /*3*/
	CH_ERROR_DOM_WRONG_DOCUMENT_ERR,          /*4*/
	CH_ERROR_DOM_INVALID_CHARACTER_ERR,       /*5*/
	CH_ERROR_DOM_NO_DATA_ALLOWED_ERR,         /*6*/
	CH_ERROR_DOM_NO_MODIFICATION_ALLOWED_ERR, /*7*/
	CH_ERROR_DOM_NOT_FOUND_ERR,               /*8*/
	CH_ERROR_DOM_NOT_SUPPORTED_ERR,           /*9*/
	CH_ERROR_DOM_INUSE_ATTRIBUTE_ERR,         /*10*/
	
	/* DOM error codes from http://www.w3.org/TR/DOM-Level-2/ */
	CH_ERROR_DOM_INVALID_STATE_ERR,          /*11*/
	CH_ERROR_DOM_SYNTAX_ERR,                 /*12*/
	CH_ERROR_DOM_INVALID_MODIFICATION_ERR,   /*13*/
	CH_ERROR_DOM_NAMESPACE_ERR,              /*14*/
	CH_ERROR_DOM_INVALID_ACCESS_ERR,         /*15*/

	/* DOM error codes from http://www.w3.org/TR/DOM-Level-2/range.html */
	CH_ERROR_DOM_RANGE_BAD_BOUNDARYPOINTS_ERR,/*1*/
	CH_ERROR_DOM_RANGE_INVALID_NODE_TYPE_ERR, /*2*/

	/* DOM error codes defined by us */
	CH_ERROR_DOM_SECURITY_ERR,               /*1000*/
	CH_ERROR_DOM_SECMAN_ERR,                 /*1001*/
	CH_ERROR_DOM_WRONG_TYPE_ERR,             /*1002*/
	CH_ERROR_DOM_NOT_OBJECT_ERR,             /*1003*/
	CH_ERROR_DOM_NOT_XPC_OBJECT_ERR,         /*1004*/
	CH_ERROR_DOM_NOT_NUMBER_ERR,             /*1005*/
	CH_ERROR_DOM_NOT_BOOLEAN_ERR,            /*1006*/
	CH_ERROR_DOM_NOT_FUNCTION_ERR,           /*1007*/
	CH_ERROR_DOM_TOO_FEW_PARAMETERS_ERR,     /*1008*/
	CH_ERROR_DOM_BAD_DOCUMENT_DOMAIN,        /*1009*/
	CH_ERROR_DOM_PROP_ACCESS_DENIED,          /*1010*/
	CH_ERROR_DOM_XPCONNECT_ACCESS_DENIED,     /*1011*/
	CH_ERROR_DOM_BAD_URI,                     /*1012*/
	CH_ERROR_DOM_RETVAL_UNDEFINED,            /*1013*/
	
	CH_FRAME_MGR_PROP_NOT_THERE,
	CH_ERROR_NOT_IMPLEMENTED
}CH_STATUS;


#endif 
