#
# makefile
#
# Copyright (C) STMicroelectronics Limited 2002. All rights reserved.
#
# Makefile for the EMBX2 benchmark test
#

TESTS         = burst leak overflow thread

RPC_TEST = ..
include $(RPC_TEST)/harness/harness.mak
