
#include <stdlib.h>
#include <string.h>

#include "370_VSB_init.h"
#include "370_VSB_map.h"

ST_ErrorCode_t STB0370_VSB_Init(STTUNER_IOREG_DeviceMap_t *DeviceMap)
{
     U32             *DefVal;

    /*
    **   REGISTER CONFIGURATION
    **     ----------------------
    */
      DefVal = DeviceMap->DefVal;
		
/*	REGISTER INITIALISATION	*/
/*	ID	*/
STTUNER_IOREG_AddReg(DeviceMap,R_ID,0xf000,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_ID,IDENTIFICATIONREGISTER,0,8,FIELD_TYPE_UNSIGNED);

/*	I2C_PAGE	*/
STTUNER_IOREG_AddReg(DeviceMap,R_I2C_PAGE,0xf001,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_I2C_PAGE,REG_PAGE_ADRESS,0,4,FIELD_TYPE_UNSIGNED);

/*	I2CRPT1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_I2CRPT1,0xf002,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_I2CRPT1,I2CT_ON_1,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_I2CRPT1,ENARPT_LEVEL_1,4,3,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_I2CRPT1,SCLT_DELAY_1,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_I2CRPT1,SCLT_NOD_1,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_I2CRPT1,STOP_ENABLE_1,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_I2CRPT1,SDAT_NOD_1,0,1,FIELD_TYPE_UNSIGNED);

/*	I2CRPT2	*/
STTUNER_IOREG_AddReg(DeviceMap,R_I2CRPT2,0xf003,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_I2CRPT2,I2CT_ON_2,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_I2CRPT2,ENARPT_LEVEL_2,4,3,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_I2CRPT2,SCLT_DELAY_2,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_I2CRPT2,SCLT_NOD_2,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_I2CRPT2,STOP_ENABLE_2,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_I2CRPT2,SDAT_NOD_2,0,1,FIELD_TYPE_UNSIGNED);

/*	CLK_CTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CLK_CTRL,0xf004,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CLK_CTRL,CLKDIVQAM_DIS,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_CLK_CTRL,EN_EXTCLK_VSB,6,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_CLK_CTRL,EN_EXTCLK_QAM,5,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_CLK_CTRL,CLK50_QAM,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_CLK_CTRL,CLK50_VSBDEM,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_CLK_CTRL,EN_CLKOSC,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_CLK_CTRL,BYPASS_PLL,0,1,FIELD_TYPE_UNSIGNED);

/*	STANDBY	*/
STTUNER_IOREG_AddReg(DeviceMap,R_STANDBY,0xf005,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_STANDBY,STANDBY_TUNER,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_STANDBY,STANDBY_NCO,6,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_STANDBY,STANDBY_AD10,5,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_STANDBY,STANDBY_OOB,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_STANDBY,STANDBY_QAM,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_STANDBY,STANDBY_VSB,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_STANDBY,SEL_VSB,0,1,FIELD_TYPE_UNSIGNED);

/*	IO_CTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_IO_CTRL,0xf006,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_IO_CTRL,TS_HIGHZ,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_IO_CTRL,OOB_OUT_HIGHZ,6,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_IO_CTRL,ACI_IO_NOD,5,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_IO_CTRL,AGC1_VSB_NOD,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_IO_CTRL,AGC2_VSB_NOD,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_IO_CTRL,AGC1_QAM_NOD,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_IO_CTRL,AGC2_QAM_NOD,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_IO_CTRL,AGC_OOB_NOD,0,1,FIELD_TYPE_UNSIGNED);

/*	GPIO_INFO	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GPIO_INFO,0xf007,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GPIO_INFO,ACI_3PINS,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_GPIO_INFO,SETINFO,0,3,FIELD_TYPE_UNSIGNED);

/*	AD_INTERF	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AD_INTERF,0xf640,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AD_INTERF,INV_CLK_AD8,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AD_INTERF,DIS_SYNC_AD8,6,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AD_INTERF,FIFO_STOP,5,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AD_INTERF,QAM_FIFO_SRST,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AD_INTERF,VSB_FIFO_SRST,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AD_INTERF,INV_CLK_AD10,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AD_INTERF,DIS_FIFO,0,1,FIELD_TYPE_UNSIGNED);

/*	TEST_AD_IF	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TEST_AD_IF,0xf641,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TEST_AD_IF,SEL_OUT_AD8,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TEST_AD_IF,SEL_OUT_AD10,2,2,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TEST_AD_IF,DSAMPLE_RAT,0,2,FIELD_TYPE_UNSIGNED);

/*	PLL_CTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_PLL_CTRL,0xf610,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_PLL_CTRL,EN_CLKAD10,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_PLL_CTRL,EN_CLKAD8,6,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_PLL_CTRL,RFILT,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_PLL_CTRL,SELICP,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_PLL_CTRL,DIV,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_PLL_CTRL,NOT_PWR_DN,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_PLL_CTRL,NOT_RESET,0,1,FIELD_TYPE_UNSIGNED);

/*	PLL_TEST	*/
STTUNER_IOREG_AddReg(DeviceMap,R_PLL_TEST,0xf611,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_PLL_TEST,SEL12DIV,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_PLL_TEST,TESTDIV_VSB,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_PLL_TEST,EN_BYP_DIV34,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_PLL_TEST,PFD,0,2,FIELD_TYPE_UNSIGNED);

/*	NCO_PLL1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCO_PLL1,0xf612,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_PLL1,RFILT1,5,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_PLL1,SELICP1,3,2,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_PLL1,MDIV,1,2,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_PLL1,NOT_PWR_DN1,0,1,FIELD_TYPE_UNSIGNED);

/*	NCO_PLL2	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCO_PLL2,0xf613,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_PLL2,RFILT2,5,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_PLL2,SELICP2,3,2,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_PLL2,NOT_PWR_DN2,0,1,FIELD_TYPE_UNSIGNED);

/*	NCO_TST_PLL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCO_TST_PLL,0xf614,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_TST_PLL,PFD_PLL2,4,2,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_TST_PLL,EN_TESTCLKIN2,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_TST_PLL,PFD_PLL1,1,2,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_TST_PLL,EN_TESTCLKIN1,0,1,FIELD_TYPE_UNSIGNED);

/*	NCO_CTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCO_CTRL,0xf615,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_CTRL,ENPRG,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_CTRL,SDIV,2,2,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_CTRL,NRSTM11,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_CTRL,NRST,0,1,FIELD_TYPE_UNSIGNED);

/*	NCO_SYNTH_COARSE_FREQ	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCO_SYNTH_COARSE_FREQ,0xf616,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_SYNTH_COARSE_FREQ,MD,0,5,FIELD_TYPE_UNSIGNED);

/*	NCO_SYNTH_FINE_FREQ_1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCO_SYNTH_FINE_FREQ_1,0xf617,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_SYNTH_FINE_FREQ_1,PE_MSB,0,7,FIELD_TYPE_UNSIGNED);

/*	NCO_SYNTH_FINE_FREQ_0	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCO_SYNTH_FINE_FREQ_0,0xf618,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_SYNTH_FINE_FREQ_0,PE_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	OOB_TUNER_CTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_OOB_TUNER_CTRL,0xf619,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_OOB_TUNER_CTRL,ONTESTBUF,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_OOB_TUNER_CTRL,MUXSEL,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_OOB_TUNER_CTRL,VLOSEL,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_OOB_TUNER_CTRL,NPDAD8,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_OOB_TUNER_CTRL,NPDIF,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_OOB_TUNER_CTRL,NPDRF,0,1,FIELD_TYPE_UNSIGNED);

/*	AD10_CTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AD10_CTRL,0xf61c,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AD10_CTRL,SEL_AGC,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AD10_CTRL,SEL_VSB_QAM,5,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AD10_CTRL,INMODE,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AD10_CTRL,ECO,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AD10_CTRL,PWR_DN_MUX,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AD10_CTRL,PWR_OFF_REF,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AD10_CTRL,PWR_OFF,0,1,FIELD_TYPE_UNSIGNED);


/*	DEMOD_CTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DEMOD_CTRL,0xf010,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DEMOD_CTRL,AGC_FREEZE,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DEMOD_CTRL,NCO_FREEZE,6,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DEMOD_CTRL,VCXO_FREEZE,5,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DEMOD_CTRL,A2DTYPE,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DEMOD_CTRL,INV_IQ,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DEMOD_CTRL,RST_TIMING,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DEMOD_CTRL,RST_CARRIER,0,1,FIELD_TYPE_UNSIGNED);

/*	SYNCCTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SYNCCTRL,0xf011,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SYNCCTRL,INVCNST,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_SYNCCTRL,DCFREEZE,0,1,FIELD_TYPE_UNSIGNED);

/*	AGCCTRL1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGCCTRL1,0xf012,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGCCTRL1,TAGCDIR,6,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AGCCTRL1,IAGCDIR,5,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AGCCTRL1,TST_PWM,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AGCCTRL1,INV_PWM,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AGCCTRL1,FRZAGCRF,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AGCCTRL1,FRZAGCIF,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_AGCCTRL1,RSTAGC,0,1,FIELD_TYPE_UNSIGNED);

/*	AGCCTRL2	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGCCTRL2,0xf013,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGCCTRL2,ACCUMRSTSEL,0,3,FIELD_TYPE_UNSIGNED);

/*	AGCPWR_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGCPWR_LSB,0xf014,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGCPWR_LSB,AGCPWR_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	AGCPWR_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGCPWR_MSB,0xf015,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGCPWR_MSB,AGCPWR_MSB,0,2,FIELD_TYPE_UNSIGNED);

/*	AGCITHUP_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGCITHUP_LSB,0xf016,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGCITHUP_LSB,AGCITHUP_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	AGCITHUP_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGCITHUP_MSB,0xf017,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGCITHUP_MSB,AGCITHUP_MSB,0,4,FIELD_TYPE_UNSIGNED);

/*	AGCITHLOW_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGCITHLOW_LSB,0xf018,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGCITHLOW_LSB,AGCITHLOW_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	AGCITHLOW_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGCITHLOW_MSB,0xf019,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGCITHLOW_MSB,AGCITHLOW_MSB,0,4,FIELD_TYPE_UNSIGNED);

/*	AGCTH_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGCTH_LSB,0xf01a,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGCTH_LSB,AGCTH_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	AGCTH_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGCTH_MSB,0xf01b,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGCTH_MSB,AGCTH_MSB,0,4,FIELD_TYPE_UNSIGNED);

/*	AGCBWSEL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGCBWSEL,0xf01c,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGCBWSEL,AGCBWSEL,0,4,FIELD_TYPE_UNSIGNED);

/*	TAGCBWSEL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TAGCBWSEL,0xf01d,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TAGCBWSEL,TAGCBWSEL,0,3,FIELD_TYPE_UNSIGNED);

/*	TST_PWM1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TST_PWM1,0xf01e,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TST_PWM1,PWMINRF_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	TST_PWM2	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TST_PWM2,0xf01f,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TST_PWM2,PWMINIF_LSB,4,4,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TST_PWM2,PWMINRF_MSB,0,4,FIELD_TYPE_UNSIGNED);

/*	TST_PWM3	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TST_PWM3,0xf020,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TST_PWM3,PWMINIF_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	AGC_IND_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGC_IND_LSB,0xf021,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGC_IND_LSB,AGC_IND_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	AGC_IND_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGC_IND_MSB,0xf022,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGC_IND_MSB,AGC_IND_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	AGC_IND_MMSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_AGC_IND_MMSB,0xf023,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_AGC_IND_MMSB,AGC_IND_MMSB,0,2,FIELD_TYPE_UNSIGNED);

/*	VCXOOFFSET1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_VCXOOFFSET1,0xf024,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_VCXOOFFSET1,VCXOOFFSET1,0,8,FIELD_TYPE_UNSIGNED);

/*	VCXOOFFSET2	*/
STTUNER_IOREG_AddReg(DeviceMap,R_VCXOOFFSET2,0xf025,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_VCXOOFFSET2,VCXOOFFSET2,0,8,FIELD_TYPE_UNSIGNED);

/*	VCXOOFFSET3	*/
STTUNER_IOREG_AddReg(DeviceMap,R_VCXOOFFSET3,0xf026,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_VCXOOFFSET3,VCXOOFFSET3,0,8,FIELD_TYPE_UNSIGNED);

/*	VCXOOFFSET4	*/
STTUNER_IOREG_AddReg(DeviceMap,R_VCXOOFFSET4,0xf027,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_VCXOOFFSET4,VCXOOFFSET4,0,7,FIELD_TYPE_UNSIGNED);

/*	GAINSRC_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAINSRC_LSB,0xf028,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAINSRC_LSB,GAINSRC_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	GAINSRC_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAINSRC_MSB,0xf029,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAINSRC_MSB,GAINSRC_MSB,0,1,FIELD_TYPE_UNSIGNED);

/*	VCXOINITV	*/
STTUNER_IOREG_AddReg(DeviceMap,R_VCXOINITV,0xf02a,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_VCXOINITV,VCXOINITV,0,8,FIELD_TYPE_UNSIGNED);

/*	GAIN1ACQ1_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN1ACQ1_LSB,0xf02b,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN1ACQ1_LSB,GAIN1ACQ1_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	GAIN1ACQ1_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN1ACQ1_MSB,0xf02c,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN1ACQ1_MSB,GAIN1ACQ1_MSB,0,2,FIELD_TYPE_UNSIGNED);

/*	GAIN1ACQ2_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN1ACQ2_LSB,0xf02d,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN1ACQ2_LSB,GAIN1ACQ2_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	GAIN1ACQ2_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN1ACQ2_MSB,0xf02e,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN1ACQ2_MSB,GAIN1ACQ2_MSB,0,2,FIELD_TYPE_UNSIGNED);

/*	GAIN1TRACK_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN1TRACK_LSB,0xf02f,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN1TRACK_LSB,GAIN1TRACK_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	GAIN1TRACK_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN1TRACK_MSB,0xf030,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN1TRACK_MSB,GAIN1TRACK_MSB,0,2,FIELD_TYPE_UNSIGNED);

/*	GAIN2ACQ1_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN2ACQ1_LSB,0xf031,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN2ACQ1_LSB,GAIN2ACQ1_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	GAIN2ACQ1_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN2ACQ1_MSB,0xf032,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN2ACQ1_MSB,GAIN2ACQ1_MSB,0,2,FIELD_TYPE_UNSIGNED);

/*	GAIN2ACQ2_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN2ACQ2_LSB,0xf033,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN2ACQ2_LSB,GAIN2ACQ2_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	GAIN2ACQ2_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN2ACQ2_MSB,0xf034,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN2ACQ2_MSB,GAIN2ACQ2_MSB,0,2,FIELD_TYPE_UNSIGNED);

/*	GAIN2TRK_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN2TRK_LSB,0xf035,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN2TRK_LSB,GAIN2TRK_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	GAIN2TRK_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN2TRK_MSB,0xf036,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN2TRK_MSB,GAIN2TRK_MSB,0,2,FIELD_TYPE_UNSIGNED);

/*	GAIN3ACQ	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN3ACQ,0xf037,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN3ACQ,GAIN3ACQ,0,8,FIELD_TYPE_UNSIGNED);

/*	GAIN3TRK	*/
STTUNER_IOREG_AddReg(DeviceMap,R_GAIN3TRK,0xf038,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_GAIN3TRK,GAIN3TRK,0,8,FIELD_TYPE_UNSIGNED);

/*	VCXOERR_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_VCXOERR_LSB,0xf039,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_VCXOERR_LSB,VCXO_ERR_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	VCXOERR_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_VCXOERR_MSB,0xf03a,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_VCXOERR_MSB,VCXOERR_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	VCXOERR_MMSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_VCXOERR_MMSB,0xf03b,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_VCXOERR_MMSB,VCXOERR_MMSB,0,8,FIELD_TYPE_UNSIGNED);

/*	TIMLOCKDETECT_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TIMLOCKDETECT_LSB,0xf03c,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TIMLOCKDETECT_LSB,TIMLOCKDETECT_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	TIMLOCKDETECT_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TIMLOCKDETECT_MSB,0xf03d,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TIMLOCKDETECT_MSB,TIMLOCKDETECT_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	TIMLOCKDETECT_MMSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TIMLOCKDETECT_MMSB,0xf03e,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TIMLOCKDETECT_MMSB,FREQ_LOCK,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TIMLOCKDETECT_MMSB,TIMLOCKDETECT_MMSB,0,2,FIELD_TYPE_UNSIGNED);

/*	FREQLOCK_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_FREQLOCK_LSB,0xf03f,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_FREQLOCK_LSB,FREQLOCKTH_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	FREQLOCK_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_FREQLOCK_MSB,0xf040,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_FREQLOCK_MSB,FREQLOCKTH_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	FREQLOCK_MMSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_FREQLOCK_MMSB,0xf041,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_FREQLOCK_MMSB,FREQLOCKTH_MMSB,0,2,FIELD_TYPE_UNSIGNED);

/*	TIMINGAGCREF_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TIMINGAGCREF_LSB,0xf042,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TIMINGAGCREF_LSB,TIMINGAGCREF_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	TIMINGAGCREF_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TIMINGAGCREF_MSB,0xf043,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TIMINGAGCREF_MSB,TIMINGAGCREF_MSB,0,4,FIELD_TYPE_UNSIGNED);

/*	NCOCNST_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCOCNST_LSB,0xf044,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCOCNST_LSB,NCOCNST_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	NCOCNST_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCOCNST_MSB,0xf045,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCOCNST_MSB,NCOCNST_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	NCOCNST_MMSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCOCNST_MMSB,0xf046,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCOCNST_MMSB,NCOCNST_MMSB,0,7,FIELD_TYPE_UNSIGNED);

/*	NCOGAIN1ACQ	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCOGAIN1ACQ,0xf047,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCOGAIN1ACQ,NCOGAIN1ACQ,0,8,FIELD_TYPE_UNSIGNED);

/*	NCOGAIN1TRACK	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCOGAIN1TRACK,0xf048,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCOGAIN1TRACK,NCOGAIN1TRACK,0,8,FIELD_TYPE_UNSIGNED);

/*	NCOGAIN2ACQ	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCOGAIN2ACQ,0xf049,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCOGAIN2ACQ,NCOGAIN2ACQ,0,8,FIELD_TYPE_UNSIGNED);

/*	NCOGAIN2TRACK	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCOGAIN2TRACK,0xf04a,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCOGAIN2TRACK,NCOGAIN2TRACK,0,8,FIELD_TYPE_UNSIGNED);

/*	NCOGAIN3	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCOGAIN3,0xf04b,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCOGAIN3,NCOGAIN3,0,8,FIELD_TYPE_UNSIGNED);

/*	NCOERR_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCOERR_LSB,0xf04c,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCOERR_LSB,NCOERR_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	NCOERR_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCOERR_MSB,0xf04d,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCOERR_MSB,NCOERR_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	NCOERR_MMSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCOERR_MMSB,0xf04e,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCOERR_MMSB,NCOERR_MMSB,0,1,FIELD_TYPE_UNSIGNED);/*This is changed to 1 bit from 2 bit. */

/*	CARLOCKDETECT1_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CARLOCKDETECT1_LSB,0xf04f,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CARLOCKDETECT1_LSB,CARLOCKDETECT1_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	CARLOCKDETECT1_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CARLOCKDETECT1_MSB,0xf050,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CARLOCKDETECT1_MSB,CARLOCKDETECT1_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	CARLOCKDETECT1_MMSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CARLOCKDETECT1_MMSB,0xf051,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CARLOCKDETECT1_MMSB,CY_LOCK,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_CARLOCKDETECT1_MMSB,CARLOCKDETECT1_MMSB,0,2,FIELD_TYPE_UNSIGNED);

/*	CARLOCKDETECT2_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CARLOCKDETECT2_LSB,0xf052,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CARLOCKDETECT2_LSB,CARLOCKDETECT2_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	CARLOCKDETECT2_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CARLOCKDETECT2_MSB,0xf053,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CARLOCKDETECT2_MSB,CARLOCKDETECT2_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	CARLOCKDETECT2_MMSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CARLOCKDETECT2_MMSB,0xf054,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CARLOCKDETECT2_MMSB,CARLOCKDETECT2_MMSB,0,2,FIELD_TYPE_UNSIGNED);

/*	CARRIERLOCKTH_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CARRIERLOCKTH_LSB,0xf055,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CARRIERLOCKTH_LSB,CARRIERLOCKTH_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	CARRIERLOCKTH_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CARRIERLOCKTH_MSB,0xf056,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CARRIERLOCKTH_MSB,CARRIERLOCKTH_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	CARRIERLOCKTH_MMSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CARRIERLOCKTH_MMSB,0xf057,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CARRIERLOCKTH_MMSB,CARRIERLOCKTH_MMSB,0,2,FIELD_TYPE_UNSIGNED);

/*	CARRIERAGCREF_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CARRIERAGCREF_LSB,0xf058,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CARRIERAGCREF_LSB,CARRIERAGCREF_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	CARRIERAGCREF_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CARRIERAGCREF_MSB,0xf059,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CARRIERAGCREF_MSB,CARRIERAGCREF_MSB,0,4,FIELD_TYPE_UNSIGNED);

/*	CARAGCMIXRATIO	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CARAGCMIXRATIO,0xf05a,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CARAGCMIXRATIO,CARAGCMIXRATIO,0,3,FIELD_TYPE_UNSIGNED);

/*	FSM1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_FSM1,0xf05b,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_FSM1,RSTFSM1,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_FSM1,FRZFSM1,0,7,FIELD_TYPE_UNSIGNED);

/*	FSM2	*/
STTUNER_IOREG_AddReg(DeviceMap,R_FSM2,0xf05c,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_FSM2,RSTFSM2,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_FSM2,FRZFSM2,0,5,FIELD_TYPE_UNSIGNED);

/*	MAINSMUP	*/
STTUNER_IOREG_AddReg(DeviceMap,R_MAINSMUP,0xf05d,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_MAINSMUP,MAINSMUP,0,8,FIELD_TYPE_UNSIGNED);

/*	EQSMUP	*/
STTUNER_IOREG_AddReg(DeviceMap,R_EQSMUP,0xf05e,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_EQSMUP,EQSMUP,0,8,FIELD_TYPE_UNSIGNED);

/*	STATEVAL_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_STATEVAL_LSB,0xf05f,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_STATEVAL_LSB,STATEVAL_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	STATEVAL_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_STATEVAL_MSB,0xf060,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_STATEVAL_MSB,STATEVAL_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	STATEVAL_MMSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_STATEVAL_MMSB,0xf061,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_STATEVAL_MMSB,STATEVAL_MMSB,0,3,FIELD_TYPE_UNSIGNED);

/*	UPDATEVCXO_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_UPDATEVCXO_LSB,0xf062,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_UPDATEVCXO_LSB,UPDATEVCXO_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	UPDATEVCXO_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_UPDATEVCXO_MSB,0xf063,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_UPDATEVCXO_MSB,UPDATEVCXO_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	UPDATEVCXO_MMSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_UPDATEVCXO_MMSB,0xf064,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_UPDATEVCXO_MMSB,UPDATEVCXO_MMSB,0,3,FIELD_TYPE_UNSIGNED);

/*	MAXNBFRAMERCA	*/
STTUNER_IOREG_AddReg(DeviceMap,R_MAXNBFRAMERCA,0xf065,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_MAXNBFRAMERCA,MAXNBFRAMERCA,0,6,FIELD_TYPE_UNSIGNED);

/*	MAXNBFRAMEDD_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_MAXNBFRAMEDD_LSB,0xf066,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_MAXNBFRAMEDD_LSB,MAXNBFRAMEDD_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	MAXNBFRAMEDD_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_MAXNBFRAMEDD_MSB,0xf067,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_MAXNBFRAMEDD_MSB,MAXNBFRAMEDD_MSB,0,1,FIELD_TYPE_UNSIGNED);

/*	NCO_TIMEOUT_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCO_TIMEOUT_LSB,0xf068,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_TIMEOUT_LSB,NCO_TIMEOUT_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	NCO_TIMEOUT_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCO_TIMEOUT_MSB,0xf069,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_TIMEOUT_MSB,NCO_TIMEOUT_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	NCO_TIMEOUT_MMSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_NCO_TIMEOUT_MMSB,0xf06a,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_NCO_TIMEOUT_MMSB,NCO_TIMEOUT_MMSB,0,8,FIELD_TYPE_UNSIGNED);

/*	DEMSTATUS	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DEMSTATUS,0xf06b,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DEMSTATUS,EQSTATE,4,4,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DEMSTATUS,MAINSTATE,0,4,FIELD_TYPE_UNSIGNED);

/*	SYSCTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SYSCTRL,0xf06c,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SYSCTRL,STATE_SHUNT,0,1,FIELD_TYPE_UNSIGNED);

/*	SEG_INIT_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SEG_INIT_LSB,0xf06d,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SEG_INIT_LSB,SEG_INIT_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	SEG_INIT_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SEG_INIT_MSB,0xf06e,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SEG_INIT_MSB,SEG_INIT_MSB,0,3,FIELD_TYPE_UNSIGNED);

/*	CENTROIDCALDONE_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CENTROIDCALDONE_LSB,0xf06f,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CENTROIDCALDONE_LSB,CENTROIDCALDONE_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	CENTROIDCALDONE_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CENTROIDCALDONE_MSB,0xf070,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CENTROIDCALDONE_MSB,CENTROIDCALDONE_MSB,0,3,FIELD_TYPE_UNSIGNED);

/*	CENTROIDOFFSET_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CENTROIDOFFSET_LSB,0xf071,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CENTROIDOFFSET_LSB,CENTROIDOFFSET_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	CENTROIDOFFSET_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CENTROIDOFFSET_MSB,0xf072,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CENTROIDOFFSET_MSB,CENTROIDOFFSET_MSB,0,2,FIELD_TYPE_UNSIGNED);

/*	FFEGAINTRAIN	*/
STTUNER_IOREG_AddReg(DeviceMap,R_FFEGAINTRAIN,0xf073,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_FFEGAINTRAIN,FFEGAINTRAIN,0,7,FIELD_TYPE_UNSIGNED);

/*	FFEGAINRCA1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_FFEGAINRCA1,0xf074,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_FFEGAINRCA1,FFEGAINRCA1,0,7,FIELD_TYPE_UNSIGNED);

/*	FFEGAINRCA2	*/
STTUNER_IOREG_AddReg(DeviceMap,R_FFEGAINRCA2,0xf075,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_FFEGAINRCA2,FFEGAINRCA2,0,7,FIELD_TYPE_UNSIGNED);

/*	FFEGAINDDM1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_FFEGAINDDM1,0xf076,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_FFEGAINDDM1,FFEGAINDDM1,0,7,FIELD_TYPE_UNSIGNED);

/*	FFEGAINDDM2	*/
STTUNER_IOREG_AddReg(DeviceMap,R_FFEGAINDDM2,0xf077,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_FFEGAINDDM2,FFEGAINDDM2,0,7,FIELD_TYPE_UNSIGNED);

/*	DFEGAINTRAIN	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DFEGAINTRAIN,0xf078,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DFEGAINTRAIN,DFEGAINTRAIN,0,7,FIELD_TYPE_UNSIGNED);

/*	DFEGAINRCA1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DFEGAINRCA1,0xf079,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DFEGAINRCA1,DFEGAINRCA1,0,7,FIELD_TYPE_UNSIGNED);

/*	DFEGAINRCA2	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DFEGAINRCA2,0xf07a,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DFEGAINRCA2,DFEGAINRCA2,0,7,FIELD_TYPE_UNSIGNED);

/*	DFEGAINDDM1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DFEGAINDDM1,0xf07b,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DFEGAINDDM1,DFEGAINDDM1,0,7,FIELD_TYPE_UNSIGNED);

/*	DFEGAINDDM2	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DFEGAINDDM2,0xf07c,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DFEGAINDDM2,DFEGAINDDM2,0,7,FIELD_TYPE_UNSIGNED);

/*	SNR_TH_DDM1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SNR_TH_DDM1,0xf07d,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SNR_TH_DDM1,SNR_TH_DDM1_UP,4,4,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_SNR_TH_DDM1,SNR_TH_DDM1_DOWN,0,4,FIELD_TYPE_UNSIGNED);

/*	SNR_TH_DDM2	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SNR_TH_DDM2,0xf07e,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SNR_TH_DDM2,SNR_TH_DDM2_UP,4,4,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_SNR_TH_DDM2,SNR_TH_DDM2_DOWN,0,4,FIELD_TYPE_UNSIGNED);

/*	SNR_TH_PT	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SNR_TH_PT,0xf07f,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SNR_TH_PT,SNR_TH_PT_UP,4,4,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_SNR_TH_PT,SNR_TH_PT_DOWN,0,4,FIELD_TYPE_UNSIGNED);

/*	SNR_TH_RCA1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SNR_TH_RCA1,0xf080,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SNR_TH_RCA1,SNR_TH_RCA1_UP,4,4,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_SNR_TH_RCA1,SNR_TH_RCA1_DOWN,0,4,FIELD_TYPE_UNSIGNED);

/*	SNR_TH_RCA2	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SNR_TH_RCA2,0xf081,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SNR_TH_RCA2,SNR_TH_RCA2_UP,4,4,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_SNR_TH_RCA2,SNR_TH_RCA2_DOWN,0,4,FIELD_TYPE_UNSIGNED);

/*	LEAKFFETRAIN	*/
STTUNER_IOREG_AddReg(DeviceMap,R_LEAKFFETRAIN,0xf082,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_LEAKFFETRAIN,LEAKFFETRAIN,0,4,FIELD_TYPE_UNSIGNED);

/*	LEAKFFERCA	*/
STTUNER_IOREG_AddReg(DeviceMap,R_LEAKFFERCA,0xf083,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_LEAKFFERCA,LEAKFFERCATRACK,4,4,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_LEAKFFERCA,LEAKFFERCAACQ,0,4,FIELD_TYPE_UNSIGNED);

/*	LEAKFFEDDM	*/
STTUNER_IOREG_AddReg(DeviceMap,R_LEAKFFEDDM,0xf084,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_LEAKFFEDDM,LEAKFFEDDM2,4,4,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_LEAKFFEDDM,LEAKFFEDDM1,0,4,FIELD_TYPE_UNSIGNED);

/*	LEAKDFETRAIN	*/
STTUNER_IOREG_AddReg(DeviceMap,R_LEAKDFETRAIN,0xf085,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_LEAKDFETRAIN,LEAKDFETRAIN,0,4,FIELD_TYPE_UNSIGNED);

/*	LEAKDFERCA	*/
STTUNER_IOREG_AddReg(DeviceMap,R_LEAKDFERCA,0xf086,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_LEAKDFERCA,LEAKDFERCATRACK,4,4,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_LEAKDFERCA,LEAKDFERCAACQ,0,4,FIELD_TYPE_UNSIGNED);

/*	LEAKDFEDDM	*/
STTUNER_IOREG_AddReg(DeviceMap,R_LEAKDFEDDM,0xf087,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_LEAKDFEDDM,LEAKDFEDDM2,4,4,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_LEAKDFEDDM,LEAKDFEDDM1,0,4,FIELD_TYPE_UNSIGNED);

/*	TRACK_REG	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TRACK_REG,0xf088,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TRACK_REG,EQ_DAGCGAIN,5,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TRACK_REG,EQDAGCFRZ,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TRACK_REG,NCOPTGAIN,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TRACK_REG,TTFRZ,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TRACK_REG,PTGAIN,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TRACK_REG,PTFRZ,0,1,FIELD_TYPE_UNSIGNED);

/*	DFE_CTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DFE_CTRL,0xf089,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DFE_CTRL,EQSWRSTN,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DFE_CTRL,DCFILTERON,6,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DFE_CTRL,SEGSYNCTRAINEN,5,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DFE_CTRL,DFE_GO,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DFE_CTRL,DEROT_EN,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DFE_CTRL,DAGC_GO,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DFE_CTRL,DAGC_GAIN,0,2,FIELD_TYPE_UNSIGNED);

/*	TAP_CTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TAP_CTRL,0xf08a,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TAP_CTRL,CFGTAPS,6,2,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TAP_CTRL,DFE2,5,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TAP_CTRL,DFE1,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TAP_CTRL,FFE,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TAP_CTRL,WR_NRD,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TAP_CTRL,NEW_REQ,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TAP_CTRL,START,0,1,FIELD_TYPE_UNSIGNED);

/*	TAP_POINTER_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TAP_POINTER_LSB,0xf08b,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TAP_POINTER_LSB,TAP_POINTER_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	TAP_POINTER_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TAP_POINTER_MSB,0xf08c,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TAP_POINTER_MSB,TAP_POINTER_MSB,0,3,FIELD_TYPE_UNSIGNED);

/*	TAP_GETBYTE	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TAP_GETBYTE,0xf08d,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TAP_GETBYTE,TAP_GETBYTE,0,8,FIELD_TYPE_UNSIGNED);

/*	TAP_PUTBYTE	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TAP_PUTBYTE,0xf08e,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TAP_PUTBYTE,TAP_PUTBYTE,0,8,FIELD_TYPE_UNSIGNED);

/*	DECCTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DECCTRL,0xf08f,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DECCTRL,ILTSTEN,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DECCTRL,RANDFRZ,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DECCTRL,RSFRZ,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DECCTRL,PS_MODE,0,1,FIELD_TYPE_UNSIGNED);

/*	DECSYNCCTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DECSYNCCTRL,0xf090,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DECSYNCCTRL,PRST,0,1,FIELD_TYPE_UNSIGNED);

/*	SER_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SER_LSB,0xf091,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SER_LSB,SER_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	SER_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SER_MSB,0xf092,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SER_MSB,SER_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	SER_PERIOD_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SER_PERIOD_LSB,0xf093,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SER_PERIOD_LSB,SER_PERIOD_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	SER_PERIOD_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SER_PERIOD_MSB,0xf094,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SER_PERIOD_MSB,SER_PERIOD_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	DEC_STATUS	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DEC_STATUS,0xf095,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DEC_STATUS,OQMEANPWORK,6,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DEC_STATUS,FRMLOCK,5,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DEC_STATUS,FIELD,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_DEC_STATUS,VSBMODE,0,4,FIELD_TYPE_UNSIGNED);

/*	SIGNAL_POWER_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SIGNAL_POWER_LSB,0xf096,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SIGNAL_POWER_LSB,SIGNAL_POWER_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	SIGNAL_POWER_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_SIGNAL_POWER_MSB,0xf097,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_SIGNAL_POWER_MSB,SIGNAL_POWER_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	ERROR_POWER_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_ERROR_POWER_LSB,0xf098,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_ERROR_POWER_LSB,ERROR_POWER_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	ERROR_POWER_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_ERROR_POWER_MSB,0xf099,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_ERROR_POWER_MSB,ERROR_POWER_MSB,0,7,FIELD_TYPE_UNSIGNED);

/*	BERCTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_BERCTRL,0xf09a,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_BERCTRL,BERMODE,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_BERCTRL,BER_PER_UNCORR,0,7,FIELD_TYPE_UNSIGNED);

/*	BER_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_BER_LSB,0xf09b,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_BER_LSB,BER_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	BER_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_BER_MSB,0xf09c,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_BER_MSB,BER_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	BER_PERIOD_LLSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_BER_PERIOD_LLSB,0xf09d,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_BER_PERIOD_LLSB,BER_PERIOD_LLSB,0,8,FIELD_TYPE_UNSIGNED);

/*	BER_PERIOD_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_BER_PERIOD_LSB,0xf09e,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_BER_PERIOD_LSB,BER_PERIOD_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	BER_PERIOD_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_BER_PERIOD_MSB,0xf09f,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_BER_PERIOD_MSB,BER_PERIOD_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	BER_PERIOD_MMSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_BER_PERIOD_MMSB,0xf0a0,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_BER_PERIOD_MMSB,BER_PERIOD_MMSB,0,4,FIELD_TYPE_UNSIGNED);

/*	FRAMECORTH_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_FRAMECORTH_LSB,0xf0a1,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_FRAMECORTH_LSB,FRAMECORTH_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	FRAMECORTH_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_FRAMECORTH_MSB,0xf0a2,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_FRAMECORTH_MSB,FRAMECORTH_MSB,0,8,FIELD_TYPE_UNSIGNED);

/*	FRAMELOCKDELOCK	*/
STTUNER_IOREG_AddReg(DeviceMap,R_FRAMELOCKDELOCK,0xf0a3,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_FRAMELOCKDELOCK,FRAMELOCK,4,4,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_FRAMELOCKDELOCK,FRAMEDELOCK,0,4,FIELD_TYPE_UNSIGNED);

/*	CI_BYTE_CLK	*/
STTUNER_IOREG_AddReg(DeviceMap,R_CI_BYTE_CLK,0xf0a4,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_CI_BYTE_CLK,T_HIGH,4,4,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_CI_BYTE_CLK,T_LOW,0,4,FIELD_TYPE_UNSIGNED);

/*	TS_FORMAT	*/
STTUNER_IOREG_AddReg(DeviceMap,R_TS_FORMAT,0xf0a5,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_TS_FORMAT,SYNC_STRIP,4,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TS_FORMAT,SWAP,3,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TS_FORMAT,POLARITY,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TS_FORMAT,CI,1,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_TS_FORMAT,SERIES,0,1,FIELD_TYPE_UNSIGNED);

/*	ACI_CTRL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_ACI_CTRL,0xf0a6,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_ACI_CTRL,TRANSMIT,7,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_ACI_CTRL,ACI_CTRL,0,7,FIELD_TYPE_UNSIGNED);

/*	ACI_CHANNEL	*/
STTUNER_IOREG_AddReg(DeviceMap,R_ACI_CHANNEL,0xf0a7,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_ACI_CHANNEL,ACI_CHANNEL,0,7,FIELD_TYPE_UNSIGNED);

/*	ACI_PROGRAM_LSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_ACI_PROGRAM_LSB,0xf0a8,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_ACI_PROGRAM_LSB,ACI_PROGRAM_LSB,0,8,FIELD_TYPE_UNSIGNED);

/*	ACI_PROGRAM_MSB	*/
STTUNER_IOREG_AddReg(DeviceMap,R_ACI_PROGRAM_MSB,0xf0a9,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_ACI_PROGRAM_MSB,READY,2,1,FIELD_TYPE_UNSIGNED);
STTUNER_IOREG_AddField(DeviceMap,R_ACI_PROGRAM_MSB,ACI_PROGRAM_MSB,0,2,FIELD_TYPE_UNSIGNED);

/*	DELAGC_0	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DELAGC_00,0xf422,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DELAGC_00,DELAGC_00,0,8,FIELD_TYPE_UNSIGNED);

/*	DELAGC_1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DELAGC_11,0xf423,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DELAGC_11,DELAGC_11,0,8,FIELD_TYPE_UNSIGNED);

/*	DELAGC_6	*/
STTUNER_IOREG_AddReg(DeviceMap,R_DELAGC_66,0xf428,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_DELAGC_66,DELAGC_66,0,8,FIELD_TYPE_UNSIGNED);


/*	WBAGC_1	*/
STTUNER_IOREG_AddReg(DeviceMap,R_WBAGC_11,0xf432,*DefVal++);
STTUNER_IOREG_AddField(DeviceMap,R_WBAGC_11,WBAGC_11,0,8,FIELD_TYPE_UNSIGNED);

return ST_NO_ERROR;

}

  

