#
# makefile
#
# Copyright (C) STMicroelectronics Ltd. 2001
#
# Master makefile for the RPC test suite
#

SUBDIRS    = roundtrip callback primative shared string termarray vararray

RPC_TEST   = ..
include $(RPC_TEST)/harness/subdir.mak

