#
# makefile
#
# Copyright (C) STMicroelectronics Limited 2004. All rights reserved.
#
# Makefile for the MME simple test.
#

TEST          = simple

SRCS_MASTER   = host.c
SRCS_SLAVE    = companion.c simple_test.c

HDRS          = simple_test.h

RPC_TEST = ..
include $(RPC_TEST)/harness/harness.mak
