#
# makefile
#
# Copyright (C) STMicroelectronics Limited 2003. All rights reserved.
#
# Makefile for EMBX buffer_pool example
#

APP_MASTER  = producer
APP_SLAVE   = consumer

SRCS_MASTER = $(APP_MASTER).c
SRCS_SLAVE  = $(APP_SLAVE).c

include ../../harness/harness.mak
