#ifndef __LINUX_PRIORITIES_H
#define __LINUX_PRIORITIES_H

#define MIN_USER_PRIORITY				0
#define MAX_USER_PRIORITY				99


/* Sorted in increasing priority */

#define STBLAST_TASK_PRIORITY				MIN_USER_PRIORITY
#define STCC_TASK_PRIORITY				MIN_USER_PRIORITY
#define STDVM_SERVICE_TASK_PRIORITY			MIN_USER_PRIORITY
#define STEVT_USER_READ_TASK_PRIORITY			MIN_USER_PRIORITY
#define STINJ_TASK_PRIORITY				MIN_USER_PRIORITY
#define STPTI_INDEX_TASK_PRIORITY			MIN_USER_PRIORITY
#define STPTI_CAROUSEL_TASK_PRIORTY			MIN_USER_PRIORITY

#define STVIN_TASK_PRIORITY_INPUT			2

#define STBLIT_MASTER_TASK_STACK_PRIORITY		5
#define STBLIT_SLAVE_TASK_STACK_PRIORITY		5

#define STREAMING_AUDIO_DECODER_TASK_PRIORITY		6
#define AUDIO_PP_TASK_PRIORITY				6

#define STLAYER_VIDEO_HAL_TASK_PRIORITY			7

#define STVID_TASK_PRIORITY_ERROR_RECOVERY		9
#define STVID_TASK_PRIORITY_INJECTERS			9

#define PCMPLAYER_TASK_PRIORITY				10
#define SPDIFPLAYER_TASK_PRIORITY			10
#define PES_ES_PARSER_TASK_PRIORITY			10
#define STBLIT_INTERRUPT_PROCESS_TASK_STACK_PRIORITY	10
#define STLAYER_GAMMAGFX_TASK_PRIORITY			10
#define STTTX_HANDLER_TASK_PRIORITY			10
#define STVID_TASK_PRIORITY_DECODE			10
#define STVID_TASK_PRIORITY_PARSE			10

#define STVID_TASK_PRIORITY_TRICKMODE			11
#define STVID_TASK_PRIORITY_SPEED			11

#define STHDMI_TASK_CEC_PRIORITY			12
#define STPTI_EVENT_TASK_PRIORITY			12
#define STVID_TASK_PRIORITY_DISPLAY			12
#define STVOUT_TASK_CEC_PRIORITY			12
#define STVTG_TASK_PRIORITY_IT_PROCESSING		12

#define STTTX_TIMEOUT_TASK_PRIORITY			15
#define STTTX_POOLING_TASK_PRIORITY			15

#define NET_TASK_PRIORITY				16

#define STVOUT_TASK_HDCP_PRIORITY			25

#define STVOUT_TASK_INTERRUPT_PROCESS_PRIORITY		60

#define STBLAST_TIMER_TASK_PRIORITY			MAX_USER_PRIORITY
#define STCLKRV_FILTER_TASK_PRIORITY			MAX_USER_PRIORITY
#define STFDMA_CALLBACK_TASK_PRIORITY			MAX_USER_PRIORITY
#define STSMART_EVENTMGR_TASK_PRIORITY			MAX_USER_PRIORITY
#define STTUNER_SCAN_CAB_TASK_PRIORITY			MAX_USER_PRIORITY
#define STTUNER_SCAN_SAT_TASK_PRIORITY			MAX_USER_PRIORITY
#define STTUNER_SCAN_TER_TASK_PRIORITY			MAX_USER_PRIORITY
#define STPTI_INTERRUPT_TASK_PRIORITY			MAX_USER_PRIORITY
#define STUART_TIMER_TASK_PRIORIT			MAX_USER_PRIORITY

#endif
