#ifndef __OS2X_PRIORITIES_H
#define __OS2X_PRIORITIES_H

#include <task.h>	/* For MIN_USER_PRIORITY and MAX_USER_PRIORITY */

/* Sorted in increasing priority */

#define STBLAST_TASK_PRIORITY				MIN_USER_PRIORITY
#define BAT_PRIORITY					MIN_USER_PRIORITY
#define STCC_TASK_PRIORITY				MIN_USER_PRIORITY
#define STDVM_SERVICE_TASK_PRIORITY			MIN_USER_PRIORITY
#define STINJ_TASK_PRIORITY				MIN_USER_PRIORITY
#define STPTI_EVENT_TASK_PRIORITY			MIN_USER_PRIORITY
#define STPTI_INDEX_TASK_PRIORITY			MIN_USER_PRIORITY
#define STPTI_CAROUSEL_TASK_PRIORTY			MIN_USER_PRIORITY
#define STTBX_FLUSH_OUTPUT_BUFFERS_TASK_PRIORITY	MIN_USER_PRIORITY

#define STVID_TASK_PRIORITY_ERROR_RECOVERY		2
#define STVID_TASK_PRIORITY_INJECTERS			2
#define STVIN_TASK_PRIORITY_INPUT			2

#define STVID_TASK_PRIORITY_DECODE			3
#define STVID_TASK_PRIORITY_PARSE			3

#define STVID_TASK_PRIORITY_TRICKMODE			4
#define STVID_TASK_PRIORITY_SPEED			4

#define STBLIT_MASTER_TASK_STACK_PRIORITY		5
#define STBLIT_SLAVE_TASK_STACK_PRIORITY		5
#define STSUBT_TASK_PRIORITY				5
#define STVID_TASK_PRIORITY_DISPLAY			5

#define STREAMING_AUDIO_DECODER_TASK_PRIORITY		6
#define AUDIO_PP_TASK_PRIORITY				6

#ifdef ST_OS20
#define STHDMI_TASK_CEC_PRIORITY			7
#define STVOUT_TASK_CEC_PRIORITY			7
#endif

#define STDISP_VSYNC_LOW_PROCESS_TASK_PRIORITY		8

#define PCMPLAYER_TASK_PRIORITY				10
#define SPDIFPLAYER_TASK_PRIORITY			10
#define PES_ES_PARSER_TASK_PRIORITY			10
#define STBLIT_INTERRUPT_PROCESS_TASK_STACK_PRIORITY	10
#define STLAYER_GAMMAGFX_TASK_PRIORITY			10
#define STLAYER_VIDEO_HAL_TASK_PRIORITY			10
#define STTTX_HANDLER_TASK_PRIORITY			10

#define STVTG_TASK_PRIORITY_IT_PROCESSING		12

#ifdef ST_OS20
#define STVOUT_TASK_HDCP_PRIORITY			14
#endif

#define STDISP_VSYNC_HIGH_PROCESS_TASK_PRIORITY		15
#define STTTX_TIMEOUT_TASK_PRIORITY			15
#define STTTX_POOLING_TASK_PRIORITY			15
#ifdef ST_OS20
#define STVOUT_TASK_INTERRUPT_PROCESS_PRIORITY		15
#endif

#define NET_TASK_PRIORITY				16

#ifdef ST_OS21
#define STHDMI_TASK_CEC_PRIORITY			125
#define STVOUT_TASK_CEC_PRIORITY			125
#endif

#ifdef ST_OS21
#define STVOUT_TASK_HDCP_PRIORITY			(MAX_USER_PRIORITY - 5)
#endif

#ifdef ST_OS20
#define ICAM_PKT_TASK_PRIORITY				(MAX_USER_PRIORITY - 4)
#define ICAM_BCK_TASK_PRIORITY				(MAX_USER_PRIORITY - 4)
#endif

#define STBLAST_TIMER_TASK_PRIORITY			MAX_USER_PRIORITY
#define STCLKRV_FILTER_TASK_PRIORITY			MAX_USER_PRIORITY
#define STFDMA_CALLBACK_TASK_PRIORITY			MAX_USER_PRIORITY
#define STSMART_EVENTMGR_TASK_PRIORITY			MAX_USER_PRIORITY
#define STTUNER_SCAN_CAB_TASK_PRIORITY			MAX_USER_PRIORITY
#define STTUNER_SCAN_SAT_TASK_PRIORITY			MAX_USER_PRIORITY
#define STTUNER_SCAN_TER_TASK_PRIORITY			MAX_USER_PRIORITY
#define STPTI_INTERRUPT_TASK_PRIORITY			MAX_USER_PRIORITY
#define STUART_TIMER_TASK_PRIORITY			MAX_USER_PRIORITY
#ifdef ST_OS21
#define STVOUT_TASK_INTERRUPT_PROCESS_PRIORITY		MAX_USER_PRIORITY
#endif

#endif
