#
# mkfiles/makefile
#
# Copyright (C) STMicroelectronics Ltd. 2002
#
# Makefile to copy the config files into the distribution
#

RPC_ROOT=../..

include $(RPC_ROOT)/src/mkfiles/host.mak

all :

clean :

DIST_SRC = host.mak install.mak platform.mak subdir.mak \
           ia32_linux.mak ia32_winnt.mak sparc_solaris.mak \
	   st20_os20.mak st40_linux.mak st40_linux_ko.mak \
	   st40_os21.mak st40_wince.mak st220_os21.mak \
	   st231_os21.mak build.mak kbuild.mak makefile

include $(RPC_ROOT)/src/mkfiles/install.mak
