#
# makefile
#
# Copyright (C) STMicroelectronics Limited 2002. All rights reserved.
#
# Makefile for the RPC benchmark test
#

TEST              = roundtrip
ENABLE_RPC        = 1

RPC_LAYOUT        = $(TEST).h

SRCS_MASTER       = master.c
SRCS_SLAVE        = slave.c

RPC_TEST = ../..
include $(RPC_TEST)/harness/harness.mak
