#
# makefile
#
# Copyright (C) STMicroelectronics R&D Ltd. 2002
#
# Makefile for tools source subtree
#

RPC_ROOT = ../..

include $(RPC_ROOT)/src/mkfiles/host.mak

SUBDIRS = multirun
include $(RPC_ROOT)/src/mkfiles/subdir.mak

DIST_SRC = makefile
include $(RPC_ROOT)/src/mkfiles/install.mak
