#
# makefile
#
# Copyright (C) STMicroelectronics Limited 2002. All rights reserved.
#
# Makefile for the RPC benchmark test
#

TEST              = vararray
ENABLE_RPC        = 1

RPC_TEST = ../..
include $(RPC_TEST)/harness/harness.mak
