#
# makefile
#
# Copyright (C) STMicroelectronics Limited 2004. All rights reserved.
#
# Makefile for the MME simple test.
#

TEST          = buffercontent

SRCS_MASTER   = buffercontent_src.c
SRCS_SLAVE    = buffercontent_src.c

HDRS          = 

RPC_TEST = ..
include $(RPC_TEST)/harness/harness.mak
