#
# makefile
#
# Copyright (C) STMicroelectronics Limited 2003. All rights reserved.
#
# Makefile for the EMBX2 memory manager tests
#

TESTS         = bigalloc size thread

RPC_TEST = ..
include $(RPC_TEST)/harness/harness.mak
