
/*
(c) Copyright changhong
  Name:Vfd.h
  Description: head file,实现与长虹VFD显示板单片机通讯的接口函数,该VFD显示板能实现VFD显示和按键控制功能
  Authors:yixiaoli
  Date          Remark
  2007-03-12    Created

Modifiction:


*/

typedef enum
{
	DISPLAY_ON,
	DISPLAY_OFF
}CH_CELL_STATUS;

typedef enum
{
	CELL_MUTE,
	CELL_USB,
	CELL_MP3,
	CELL_HD,
	CELL_LEFTARROW,
	CELL_CH,
	CELL_POINTA,
	CELL_POINTB,
	CELL_1080I,
	CELL_720P,
	CELL_576P,
	CELL_576I,
	CELL_HDMI,
	CELL_VGA,
	CELL_YPBPR,
	CELL_VIDEO,
	CELL_TV,
	CELL_RADIO,
	CELL_TUNER0,
	CELL_LINE,
	CELL_POWER
}CH_CELL_TYPE;


typedef enum
{

	CONTROL_NOP=0X0,
	CONTROL_GREENLIGHT_ON=0X01,
	CONTROL_GREENLIGHT_OFF=0X02,
	CONTROL_YELLOWLIGHT_ON=0X03,
	CONTROL_YELLOWLIGHT_OFF=0X04,
	CONTROL_VFD_ON=0X05,
	CONTROL_VFD_OFF=0X06,
	CONTROL_POINT_ON=0X07,
	CONTROL_POINT_OFF=0X08,
	CONTROL_VFD_SET=0X09,
	CONTROL_VFD_LOGIN_OFF=0X0A,
	CONTROL_WATCHDOG_REFRESH=0X0B,
	CONTROL_WATCHDOG=0X0C,

	CONTROL_SET_RTC=0X10,
	CONTROL_SET_AUTOPOWERON=0X11,
	CONTROL_SET_AUTOPOWERON_MODE=0X12,
	CONTROL_SET_AUTOPOWEROFF=0X13,
	CONTROL_SET_AUTOPOWEROFF_MODE=0X14,
	CONTROL_SET_WARNNING=0X15,
	CONTROL_SET_WARNNING_MODE=0X16,
	CONTROL_STANDBY=0X17,

	CONTROL_READ_RTC=0X80,
	CONTROL_READ_REMOTEKEY=0X81,
	CONTROL_READ_FRONTKEY=0X82

}CH_VFD_CONTROL_TYPE;




extern BOOL CH_VFD_Init(ST_DeviceName_t I2CDeviceName);
extern BOOL CH_VFD_ClearAll(void);
extern BOOL CH_CellControl(CH_CELL_TYPE CellType,CH_CELL_STATUS CellStatus);
extern BOOL CH_VFD_WriteNumber(int StartPos,int EndPos,U32 Number);

extern BOOL CH_VFD_LOginOff(void);
extern BOOL CH_VFD_DisplayProgNumber(U32 ProgNum);
extern BOOL CH_VFD_DisplayTime(U32 Time);

extern boolean CH_VFD_ShowChar(U8 ruc_StartPos,U8 ruc_EndPos,char *rpc_String);




	
