#
# makefile
#
# Copyright (C) STMicroelectronics Limited 2002, 2003. All rights reserved.
#
# Makefile for the EMBX2 benchmark test
#

ifndef ENABLE_EMBXSHMC
TESTS         = basic overflow
endif

RPC_TEST = ..
include $(RPC_TEST)/harness/harness.mak
