#ifndef __STAT__
#define __STAT__
// It's a fake, juste for starting the project
// Will be removed as soon as we have finished the re-implementation
// of WinCE
#ifndef STAPI_QUIET
#pragma  message("-------------------------------------------------")
#pragma  message("WINCE Warning : You are including a fake STAT.h")
#pragma  message("-------------------------------------------------")
#endif
#endif
