#
# makefile
#
# Copyright (C) STMicroelectronics Ltd. 2002
#
# Makefile for examples directory
#

RPC_ROOT = ..

include $(RPC_ROOT)/src/mkfiles/host.mak

SUBDIRS = harness embx rpc $(wildcard mme)

include $(RPC_ROOT)/src/mkfiles/subdir.mak


DIST_SRC = makefile

include $(RPC_ROOT)/src/mkfiles/install.mak
