#
# makefile
#
# Copyright (C) STMicroelectronics Limited 2003. All rights reserved.
#
# Makefile for the EMBX2 port tests
#

TESTS = connection shutdown

RPC_TEST = ..
include $(RPC_TEST)/harness/harness.mak
