#
# makefile
#
# Copyright (C) STMicroelectronics Limited 2003. All rights reserved.
#
# Makefile for MME getstart example
#

ENABLE_MME  = 1

APP_MASTER  = host
APP_SLAVE   = companion

SRCS_MASTER = $(APP_MASTER).c mixer.c
SRCS_SLAVE  = $(APP_SLAVE).c mixer.c

include ../../harness/harness.mak
